### ISSUE TITLE
Please tag formal (semantic) releases

### ISSUE THREAD

**Issue by onlyjob** [coreos/go-oidc#104]

**Comment by ericchiang** [comment]
As part of this we should split the old client with the new one and have different branches.

**Comment by ericchiang** [comment]
> As part of this we should split the old client with the new one and have different branches.

@rithujohn191 can you do this at some point?

**Comment by ericchiang** [comment]
https://github.com/coreos/go-oidc/releases/tag/v2.0.0

**Comment by onlyjob** [comment]
Thanks! :)
