### ISSUE TITLE
Cache Control returns overflowed TTL

### ISSUE THREAD

**Issue by squat** [coreos/go-oidc#106]
The `cacheControlMaxHeader` function returns TTLs that overflow. I added a log at this line https://github.com/coreos/go-oidc/blob/master/http/http.go#L82 to show what the TTL was while repeatedly cURLing my app that authenticates against Dex. These logs show dramatically varying TTLs for the exact same cURL over about a five second span:

````sh
TTL:  683899h59m13.171574784s
TTL:  -770445h54m21.828425216s
TTL:  -2223611h3m7.828425216s
TTL:  1397448h29m34.8811264s
````

After more digging, it looks like the `Cache-Control: max-age=` header is being sent int nanoseconds instead of seconds, as the spec for the header requires. I tested that dividing `age` by 10^9 before parsing as a duration fixes the issue and returns sensible values for the TTL in the order of 2h48m. This is not an issue with go-oidc but most likely with the OIDC provider.

**Comment by ericchiang** [comment]
closing. This was a bug in dex. See https://github.com/coreos/dex/issues/636
