### ISSUE TITLE
example app ignores --redirect-url command line arg

### ISSUE THREAD

**Issue by bjacobowski** [coreos/go-oidc#108]
line 101 of example/app/main.go negates --redirect-url command line arg.
```go
mux.HandleFunc(pathCallback, handleCallbackFunc(c))
```
should be changed to
```go
mux.HandleFunc(cbURL.Path, handleCallbackFunc(c))
```

**Comment by ericchiang** [comment]
Since that code is no longer part of this repo, mind if I close this?
