### ISSUE TITLE
Refresh token requires id_token in response but openid spec it is optional

### ISSUE THREAD

**Issue by jsloyer** [coreos/go-oidc#111]
In the method [RefreshToken](https://github.com/coreos/go-oidc/blob/master/oidc/client.go#L755-L772), there is a line to parse the response from an OpenID provider.  The [current implementation expects](https://github.com/coreos/go-oidc/blob/master/oidc/client.go#L766) an `id_token`.  However in the [Openid spec](http://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse) it states that `id_token` is not required on the response.

**Comment by ericchiang** [comment]
Want to take a look at #110? We're just thinking of switching over to golang.org/x/oauth2 entirely and not having any explicit OAuth2 code.

**Comment by ericchiang** [comment]
@jsloyer it's a new client that let's you use `golang.org/x/oauth2`'s refreshing.

**Comment by ericchiang** [comment]
Also, out of curiosity what provider are you using that doesn't return an id_token as part of the response? I don't see how we'd update `RefreshToken` since part of its function signature is returning the id_token claims.

**Comment by jsloyer** [comment]
Could we use the `access_token` instead?

**Comment by ericchiang** [comment]
Not without breaking the API, which we're hesitant to do. If you're not expecting an id_token it seems like you'd get more use out of a plain oauth2 package instead of an OIDC one, no?

**Comment by jsloyer** [comment]
I submitted a PR to change it to AccessToken, all endpoints already return an accesstoken.
