### ISSUE TITLE
Issuer mismatch for Google: accounts.google.com vs https://accounts.google.com

### ISSUE THREAD

**Issue by bcspragu** [coreos/go-oidc#125]
According to [Google's Auth documentation](https://developers.google.com/identity/sign-in/web/backend-auth), a token will contain an issuer of `accounts.google.com` **or** `https://accounts.google.com`. In my testing, when creating a provider with `NewProvider`, the `https://...` is required, but decoded raw auth tokens contain just `accounts.google.com`, which causes an [issuer mismatch and failed verification](https://github.com/coreos/go-oidc/blob/master/oidc.go#L105). [My solution](https://github.com/bcspragu/go-oidc/commit/1ccfcb33c8965bf5dea617a31bd7919cc1be2759) was to explicitly add new issuers to `IDTokenVerifier` with an `AddIssuer` method, but substring matching or ignoring the protocol would also work, but is arguably less secure.

**Comment by ericchiang** [comment]
This seems pretty clearly against the OpenID Connect spec.

> The Issuer Identifier for the OpenID Provider (which is typically obtained during Discovery) MUST exactly match the value of the iss (issuer) Claim.

https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

When does it return `accounts.google.com`? I've always seen `https://accounts.google.com` when using google. Are you passing the `openid` scope?

**Comment by sym3tri** [comment]
Yes we encountered this with Dex v1. IIRC google doesn't implement the spec properly.

**Comment by ericchiang** [comment]
Fun!

Is the `accounts.google.com` issuer predictable based on your request or does it just randomly get inserted?

**Comment by sym3tri** [comment]
I think the issue is that Google omits the URL scheme, but the spec requires it. IIRC Dex v1 just omitted the scheme in the verification or something similar.

**Comment by ericchiang** [comment]
Sorry, I meant can you predictably get `accounts.google.com` instead of `https://accounts.google.com`. E.g. is there a scope set that triggers that behavior? I've only ever seen a id_tokens with `https://accounts.google.com`. Would be nice to know if people can just recommend people modify there requests.

We can definitely add a `VerificationOption` for this.

**Comment by ericchiang** [comment]
Blah, looks like other people have hit this https://stackoverflow.com/questions/38618826/can-i-get-a-consistent-iss-value-for-a-google-openidconnect-id-token

**Comment by ksswr** [comment]
I am consistently getting the same scheme-less response from google.

**Comment by icwr** [comment]
I am running into this issue as well :(

I modified the code to get past this by just parsing the url's and comparing hosts.
