### ISSUE TITLE
access_token verification facilities via at_hash

### ISSUE THREAD

**Issue by ericchiang** [coreos/go-oidc#126]
See: https://openid.net/specs/openid-connect-core-1_0.html#TokenRequest

At the very least we have to return what signature algorithm was used to verify an ID Token.

**Comment by gotwarlost** [comment]
I'm trying to do exactly this and the only way seems to be to reparse the token to extract the signature algorithm.

Happy to provide a PR if there is a chance it will get accepted :)

Rough sketch:

* Add a new field `signature` to hold the ID token signature after parsing. 
* Add a `VerifyAccessTokenHash` method to `IDToken` that is given an access token string and returns an error (nil on success). This uses the new signature field to derive the hash function to be used and does the verification
* Need to define semantics if this field was not set in the ID token (either succeed or return a public error variable that the caller can test for).

Thoughts?

**Comment by ericchiang** [comment]
Not a signature, just a hash.

We probably just want to make `AccessTokenHash` an exported field on the `IDToken`, then provide a `VerifyAccessToken` method.

```go
type IDToken struct {
    Issuer   string
    Audience []string
    Subject  string
    Expiry   time.Time
    IssuedAt time.Time
    Nonce    string

    AccessTokenHash string
}

func VerifyAccessToken(accessToken, accessTokenHash string) error
```

Lets the user reason about the provider not returning the `at_hash` value and what to do in that case.

**Comment by ericchiang** [comment]
Oh wait, sorry I forgot that signature algorithm plays a part in determining what hash is used.

Yeah, your approach sounds reasonable.

**Comment by gotwarlost** [comment]
Since the `VerifyAccessToken` method is bound to the `IDToken` receiver, it feels strange for the caller to have to pass it in. We already have it, right?

**Comment by gotwarlost** [comment]
anyway, let me create a PR and we can review the interface at that point

**Comment by gotwarlost** [comment]
OK, what is the target branch for the proposed PR? `master` seems to have a ton of backwards-incompatible changes from `v2`.

I'm currently using `v2` and was hoping to add this as a backwards-compatible change there.

**Comment by ericchiang** [comment]
Open a PR against v2.
