### ISSUE TITLE
Internalize more dependencies

### ISSUE THREAD

**Issue by ericchiang** [coreos/go-oidc#127]
This package has several external imports. Namely

- github.com/pquerna/cachecontrol
- ~golang.org/x/net/context~ (https://github.com/coreos/go-oidc/pull/135)
- gopkg.in/square/go-jose.v2
- golang.org/x/oauth2

As we move forward we might try to internalize some of these dependencies. E.g. context is now part of the standard library, and we might try to see if we can implement some of the cachecontrol package internally.

cc @dghubble

**Comment by dghubble** [comment]
This would make adding a go-oidc dependency more alluring. :+1:

**Comment by ericchiang** [comment]
Random musing.

The OpenID Connect spec indicates that the `Cache-Control: max-age` header is the only really supported mechanism for caching. This might be easy to implement instead of using the full `cachecontrol` package, which interprets way more headers.

https://openid.net/specs/openid-connect-core-1_0.html#RotateEncKeys

I think `golang.org/x/oauth2` is here forever, since it's exposed as part of the API.

I don't have a good answer about `gopkg.in/square/go-jose.v2`. I really don't want to implement a JWT library.

**Comment by ericchiang** [comment]
I think this would be a good effort for any v3 branch. Remove the oauth2 and cachecontrol imports. No other API changes.

**Comment by jackmcguire1** [comment]
bump, I don't need to download the google dependencies used in the example...

**Comment by ericchiang** [comment]
So realistically this would require a new major version of the package to drop the oauth2 import. The cachecontrol change would also probably be significant.

I'm totally fine with a v3, but I'd want to figure out the modules story.

**Comment by jackmcguire1** [comment]
I’m fine with any of those packages imo as it’s core functionality this module relies on, I just don’t want the bundled google dependencies, remove the example to a separate repo...

**Comment by ericchiang** [comment]
What Google dependencies are you talking about?

**Comment by ericchiang** [comment]
cachecontrol import has been removed in #259 for v3.

I don't think we'll be able to remove gopkg.in/square/go-jose.v2 or golang.org/x/oauth2 so going to call this fixed.
