### ISSUE TITLE
Session management URLs

### ISSUE THREAD

**Issue by tolleiv** [coreos/go-oidc#134]
Hi,
I'm trying to figure out how I could [end a session](http://openid.net/specs/openid-connect-session-1_0.html) / retrieve the URL from the provider to end the session. 

I'm following the examples in the repo, therefore I try to get hold of the `ProviderConfig.EndSessionEndpoint` somehow through my `Provider`object. But I can't figure out how. 

Would be nice to see an example how this could be done.

**Comment by ericchiang** [comment]
Something like this? (wrote it by hand, don't know if it'll compile)

```go
package main

import (
    "log"

    "golang.org/x/net/context"
    oidc "github.com/coreos/go-oidc"
)

func main() {
    p, err := oidc.NewProvider(context.Background, "providerurl")
    if err != nil {
        log.Fatal(err)
    }

    var sessionURLs struct {
        CheckSessionIFrame string `json:"check_session_iframe"`
        EndSessionEndpoint string `json:"end_session_endpoint"`
    }
    if err := p.Claims(&sessionURLs); err != nil {
        log.Fatal(err)
    }
}
```

**Comment by tolleiv** [comment]
Absolutely  ... thank you very much. My way to read through the code backwards was just wrong and I missed the comment pointing to the spec.

But one thing might cause some confusion for others too. The comment block along the provider.Claims methods "links" to:
  
    // For a list of fields defined by the OpenID Connect spec see:
    // https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

shouldn't that be:

    // For a list of fields defined by the OpenID Connect spec see:
    // https://openid.net/specs/openid-connect-discovery-1_0.html#rfc.section.4.2

Cheers
