### ISSUE TITLE
Error when token_endpoint_auth_methods_supported contains none

### ISSUE THREAD

**Issue by curtisallen** [coreos/go-oidc#137]
I'm attempting to use this library via Kubernetes with [okta](https://www.okta.com/) as an IDP.

When calling [oidc.FetchProviderConfig](https://github.com/kubernetes/kubernetes/blob/v1.5.3/plugin/pkg/auth/authenticator/token/oidc/oidc.go#L176) validation failes giving the error `token_endpoint_auth_signing_alg_values_supported cannot include 'none'` which comes from [this line](https://github.com/coreos/go-oidc/blob/master/oidc/provider.go#L357)

Okta's `/.well-known/openid-configuration` endpoint returns the following 
```json
...
"token_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post",
        "none"
    ]
```
After reading relevant portions of the OIDC discovery spec I don't see why go-oidc fails if `none` is in `token_endpoint_auth_methods_supported`

From https://openid.net/specs/openid-connect-discovery-1_0.html#rfc.section.3

> token_endpoint_auth_methods_supported
 > OPTIONAL. JSON array containing a list of Client Authentication methods supported by this Token Endpoint. The options are client_secret_post, client_secret_basic, client_secret_jwt, and private_key_jwt, as described in Section 9 of OpenID Connect Core 1.0 [OpenID.Core]. Other authentication methods MAY be defined by extensions. If omitted, the default is client_secret_basic -- the HTTP Basic Authentication Scheme specified in Section 2.3.1 of OAuth 2.0 [RFC6749].

It seems like `none` should be an allowed entry in `token_endpoint_auth_methods_supported` am I completely off base here?

**Comment by ericchiang** [comment]
Yeah this is a bug on our end, we should be detecting this case for

```
token_endpoint_auth_signing_alg_values_supported
```

and not

```
token_endpoint_auth_methods_supported
```

Really though we probably shouldn't be so picky about these values anyway. I'll send a patch for go-oidc but could you take a look at https://github.com/kubernetes/kubernetes/issues/42654? That's our long term plan for upstream Kubernetes.

**Comment by curtisallen** [comment]
thanks @ericchiang I'm happy to submit a pull request addressing this issue.

**Comment by ericchiang** [comment]
@curtisallen that'd be great. Please cc me and I'll review.

**Comment by mlbiam** [comment]
@ericchiang not sure "we shouldn't be picky" as much as support setting required levels.  That way we are offloading a trust level to the idp but you can show an auditor "we're meeting our auth requirements because we require XYZ"

**Comment by ericchiang** [comment]
@mlbiam I think I want to foremost be picky about the claims the package actually uses. E.g. for the more recent version of the package we enforce mandatory claims, but ignore optional ones. This is reflected in how small the provider metadata[0] and id token[1] structs are.

Enforcing optional claims is hairy business. As a package maintainer, I'd be much happier leaving provider specific claims to the provider user.

[0] https://github.com/coreos/go-oidc/blob/cf9c3b4fab2871c65040b7a4573b2e2ec1b483bb/oidc.go#L74
[1] https://github.com/coreos/go-oidc/blob/cf9c3b4fab2871c65040b7a4573b2e2ec1b483bb/oidc.go#L264
