### ISSUE TITLE
Failure on missing key id

### ISSUE THREAD

**Issue by Grillz** [coreos/go-oidc#140]
Hey, I'm trying to use this library to connect to https://github.com/ory/hydra. Everything works fine up until the final signature verification at https://github.com/coreos/go-oidc/blob/master/verify.go#L185 . The JWT headers that Hydra provides do not have `kid` as a part of them. Here is a comparison:

Hydra   
```
{
  "alg": "RS256",
  "typ": "JWT"
}
```
Google   
```
{
  "alg": "RS256",
  "kid": "fb41c2409340c77eb259a66c9f79809649a62971"
}
```

Note, the RFC on JWT's doesn't specify a `kid` parameter https://tools.ietf.org/html/rfc7519#section-5

When the verification step happens it looks for the `KeyId` that was parsed by go-jose, because its nil it fails https://github.com/coreos/go-oidc/blob/master/verify.go#L193.

I'd be happy to rewrite this algorithm 👍

**Comment by ericchiang** [comment]
Sounds good. It sounds like if there aren't any key IDs provided in the JWT, then we should check the signature against all the keys. Feel free to send a patch!

**Comment by Grillz** [comment]
exactly, I'll get started on this shortly!

**Comment by ericchiang** [comment]
Actually looking into this it seems like this library should work fine if the JWT doesn't specify a key ID and the JWK's don't have a key ID. They'll both be the empty string and everything should work.

The condition you're hitting implies that JWT isn't signed with a signing algorithm that we allow by default. What's the actual error that method is returning?

**Comment by Grillz** [comment]
Doesn't https://github.com/coreos/go-oidc/blob/master/verify.go#L193 break it? If there are no key ids present it equals 0, currently its appending a blank space `" "`, and then failing when it can't find that key id on https://github.com/coreos/go-oidc/blob/master/verify.go#L198

**Comment by ericchiang** [comment]
> If there are no key ids present it equals 0

Not quite. That condition only happens if there are no signatures with an allows signing algorithm.
```go
	var keyIDs, gotAlgs []string
	for _, sig := range jws.Signatures {
		if len(v.config.SupportedSigningAlgs) == 0 || contains(v.config.SupportedSigningAlgs, sig.Header.Algorithm) {
			keyIDs = append(keyIDs, sig.Header.KeyID)
		} else {
			gotAlgs = append(gotAlgs, sig.Header.Algorithm)
		}
	}
	if len(keyIDs) == 0 {
		return nil, fmt.Errorf("oidc: no signatures use a supported algorithm, expected %q got %q", v.config.SupportedSigningAlgs, gotAlgs)
	}
```

If the KeyID was empty, and the ID Token was signed by a an allowed algorithm, then it would still be appended to the slice and the slice length would be greater than 0.

**Comment by Grillz** [comment]
>If the KeyID was empty, and the ID Token was signed by a an allowed algorithm, then it would still be appended to the slice and the slice length would be greater than 0.

Correct the slice length is greater than zero, and then it tries and find https://github.com/coreos/go-oidc/blob/master/verify.go#L198 by key id which is `" "` So this wont evaluate https://github.com/coreos/go-oidc/blob/master/jwks.go#L88. Which causes an error

**Comment by ericchiang** [comment]
Hmmm, it's returning a blank space not an empty string? Do you have an actual id_token we could inspect? That's really weird.

**Comment by Grillz** [comment]
but its not returning a signing key either way https://github.com/coreos/go-oidc/blob/master/jwks.go#L88, which fails here https://github.com/coreos/go-oidc/blob/master/verify.go#L203

**Comment by ericchiang** [comment]
That's the expected and arguably correct behavior when the key ID is `" "`. It doesn't match the empty string key IDs of the keys.

I can confirm that if the header omits the KeyID then it just ends up as `""` not `" "`. Some how the header is getting the explicit field `kid: " "`

```go
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"os"

	jose "gopkg.in/square/go-jose.v1"
)

func encode(s string) string {
	b := new(bytes.Buffer)
	if err := json.Compact(b, []byte(s)); err != nil {
		panic(err)
	}
	return base64.RawURLEncoding.EncodeToString(b.Bytes())
}

func main() {
	header := encode(`{
		"alg": "RS256",
		"typ": "JWT"
	}`)
	payload := encode(`{
		"sub": "1234567890",
		"name": "John Doe",
		"admin": true
	}`)
	sig := `EkN-DOsnsuRjRO6BxXemmJDm3HbxrbRzXglbN2S4sOkopdU4IsDxTI8jO19W_A4K8ZPJijNLis4EZsHeY559a4DFOd50_OqgHGuERTqYZyuhtF39yxJPAjUESwxk2J5k_4zM3O-vtd1Ghyo4IbqKKSy6J9mTniYJPenn5-HIirE`
	jws, err := jose.ParseSigned(header + "." + payload + "." + sig)
	if err != nil {
		panic(err)
	}
	e := json.NewEncoder(os.Stdout)
	e.SetIndent("", "  ")
	e.Encode(jws.Signatures)
}
```

This prints

```
[
  {
    "Header": {
      "KeyID": "",
      "JsonWebKey": null,
      "Algorithm": "RS256",
      "Nonce": ""
    },
    "Signature": "EkN+DOsnsuRjRO6BxXemmJDm3HbxrbRzXglbN2S4sOkopdU4IsDxTI8jO19W/A4K8ZPJijNLis4EZsHeY559a4DFOd50/OqgHGuERTqYZyuhtF39yxJPAjUESwxk2J5k/4zM3O+vtd1Ghyo4IbqKKSy6J9mTniYJPenn5+HIirE="
  }
]
```

**Comment by ericchiang** [comment]
Again, do you have an example JWT and/or JWKS we can look at? That'd make this bug way easier to deal with.

**Comment by Grillz** [comment]
so either way if fails here https://github.com/coreos/go-oidc/blob/master/verify.go#L202, there are simply no keys present

**Comment by ericchiang** [comment]
I'm still confused by the exact bug. I wouldn't expect any key IDs to match the string `" "`, so the behavior you're reporting sounds correct.

For what it's worth, the OpenID Connect spec mandates `kid` if you have multiple keys in your JWK Set.

> If there are multiple keys in the referenced JWK Set document, a kid value MUST be provided in the JOSE Header.

**Comment by Grillz** [comment]
Ah I missed that in the OIDC RFC, was focused on the JWT Signing RFC, sorry about the running in circles, I will correct on Hydra's end then. Thanks
