### ISSUE TITLE
Provider KeySet renewal and AppEngine

### ISSUE THREAD

**Issue by someone1** [coreos/go-oidc#144]
The package works great for the most part, thank you for that! There's a bit of a flexibility issue for my usecase on AppEngine Standard. I have to initialize the provider with a context that contains a urlfetch *http.Client value, which itself is using a context that is request bound.

Basically, the provider will not retrieve a keyset until the first verify attempt, and it will use the http client found in the original context used to initialize the provider (not from the context passed to the verify call!). Since the http client I used in the Provider initializer call is bound to a context that is now cancelled, the keyset will fail fetching the resources it needs.

I believe the fix is fairly easy/straight forward and I don't foresee this being a problematic fix but leave that up to the package authors to decide. When calling the `updateKeys` function, use the context passed into to the verify call, not the context passed in when the provider was initialized.

I'll submit a PR shortly with this change.

**Comment by ericchiang** [comment]
This is documented. The context provided to the NewProvider call is supposed to be the context tied to the key set. Key sets are global to the provider, not local to individual verify calls.

**Comment by someone1** [comment]
My apologies, I do not know how I missed that. 

Do you have any suggestions on how to accommodate this situation I described? The http.DefaultClient is not available in the AppEngine Standard Go environment and the http client passed into the provider's context is only valid for a single requests lifecycle. I'd like to avoid using a global pointer that gets updated on almost every request to be updated/used in the event of a keyset refresh.

Would it make sense to take a client found in the calling context and use it over the client found in the provider's context? Or perhaps make the mechanisms for refreshing keys exported so we can renew them with a context we chose vs the providers?

I don't know how esoteric this use-case is but it would be nice to be able to use this library as it is pretty feature complete and satisfies all requirements I'm looking for.

**Comment by ericchiang** [comment]
I'm a little unclear about the exact issue you're facing. Could you elaborate a little on that?

From the top level post:

> Since the http client I used in the Provider initializer call is bound to a context that is now cancelled, the keyset will fail fetching the resources it needs.

Why did you need to cancel that context? If you kept it around you wouldn't have any issues.

**Comment by someone1** [comment]
In AppEngine Standard, you cannot make any HTTP requests without using a urlfetch client, which HAS to use a request bound context. In order to bootstrap the Provider, a urlfetch client is added to the context using the oauth2.HTTPClient key so it is used in the go-oidc package for HTTP requests. However, the keyset will not refresh/renew upon a Provider's initialization, and even if it did, subsequent keyset refreshes would try and use the HTTPClient found in the context used to bootstrap the Provider, which used a context bound to a request that is long over. The context is controlled by the AppEngine framework and not something we can keep alive past the life of the request for which it is bound to.

I hope this helps to clarify things

**Comment by ericchiang** [comment]
This sounds like you need to call NewProvider on each request then.

I don't know if we want proprietary Go environments to impact the design of this package.
