### ISSUE TITLE
The client MUST NOT use more than one authentication method in each request.

### ISSUE THREAD

**Issue by Cobi** [coreos/go-oidc#146]
In `oauth2.go`, you add `client_secret` to the `request-body`:
https://github.com/coreos/go-oidc/blob/master/oauth2/oauth2.go#L260

Then you proceed to add an `Authorization` header if the IDP supports it:
https://github.com/coreos/go-oidc/blob/master/oauth2/oauth2.go#L190

RFC6749 forbids this:
https://tools.ietf.org/html/rfc6749#section-2.3

Either use the `request-body` or the `Authorization` header for `client_secret`, not both.

**Comment by ericchiang** [comment]
The oauth2 package is deprecated. I'd suggest using golang.org/x/oauth2 instead.
