### ISSUE TITLE
Move testing providers from Kubernetes to this package

### ISSUE THREAD

**Issue by mwitkow** [coreos/go-oidc#150]
The K8s implementation has a really handy function for spinning up an `httptest`-based OIDC provider that can be useful when testing integrations of this library:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/testing/provider.go

Can we please move this to this package?

**Comment by ericchiang** [comment]
If we do I'd like to rewrite them and design them more generally. That package was written a long time ago and only for our specific use in kubernetes

**Comment by ericchiang** [comment]
These packages are going away with https://github.com/kubernetes/kubernetes/pull/58544

Agree that it'd be good to provide them, but closing for now.
