### ISSUE TITLE
Question: Supported algorithms

### ISSUE THREAD

**Issue by travisofthenorth** [coreos/go-oidc#152]
Messing around with the code, I noticed this: https://github.com/coreos/go-oidc/blob/master/jose/sig.go#L19-L21

Does this client only support RSA keys? If so, why is that and are there any plans to support additional algorithms? I personally use EC keys in my app.

**Comment by ericchiang** [comment]
The jose package is deprecated as noted in it's package documentation. So no there are no plans. We recommend square/go-jose instead.
