### ISSUE TITLE
Fail to call NewProvider()

### ISSUE THREAD

**Issue by huikang** [coreos/go-oidc#156]
Hi, I am new to OIDC. When I use the go-oidc to connect my provider, it throws the following error

```
oidc: failed to decode provider discovery object: expected Content-Type = application/json, got "text/html": invalid character '<' looking for beginning of value
```
Does the library support other content-type? If so could someone guide how to do so? Thanks.

**Comment by ericchiang** [comment]
It looks like your provider is returning HTML to it's JSON discovery endpoint. This is was a correct response looks like https://accounts.google.com/.well-known/openid-configuration

Are you sure your issuer URL is correct? For example, for google I'd have to enter "https://accounts.google.com" and then the rest of the URL is implied.

**Comment by huikang** [comment]
Hi, @ericchiang I am connecting to an internal provider. But I am not sure if _text/html_ is the only option. Does go-oidc support other content type?

**Comment by ericchiang** [comment]
> Does go-oidc support other content type?

The spec requires JSON. https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse

The content type actually isn't enforced by go-oidc. It's just mentioned if the library fails to parse the response from the provider.

**Comment by huikang** [comment]
@ericchiang you are right; it should be json format. I consulted with our internal OIDC provider team and learned that they do not support OIDC Discovery as of now. Therefore,  I need to manually configure the endpoints. Could you point me to some example using your go-oidc library? Thanks.

**Comment by ericchiang** [comment]
@huikang this package currently doesn't work with providers that don't support OIDC discovery. There's been some previous discussion previously though https://github.com/coreos/go-oidc/issues/155#issuecomment-322856151

Maybe one of those proposed API changes work for you?
