### ISSUE TITLE
Verify token on GitLab failed

### ISSUE THREAD

**Issue by Gambler13** [coreos/go-oidc#175]
I'm trying to validate a JWT token issued from GitLab.
I obtained the token from Postman without any problems. But I am not able to verify the token with go-oidc library,
When I pass the token string into the `verifier.Verify(ctx, rawIDToken)` method, I get following error: 

> failed to verify signature: failed to verify id token signature

After short debugging I saw that the key id (kid property in header) didn't match the kid obtained from the jwks uri. So for testing purpose I tried to get the key manually. But after I hit the jwks endpoint multiple times, I realized that the kid changes with every request.

So how Is it possible to verify a token issued from GitLab?

Edit:
I seems that the GitLab jwks endpoint responses with one random key of the set instead of the complete key set. After several requests I got a matching kid. But how we can handle this within go-oidc?

**Comment by ericchiang** [comment]
Thanks for reporting. I've never seen a jwks_uri endpoint returning a
rotating set of keys. Any idea why they don't return all the keys in one
request? I don't see anything like in the discovery spec:

https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

Maybe something GitLab would be interesting in fixing?

**Comment by Gambler13** [comment]
I already opened an Issue on GitLab, but still no response
https://gitlab.com/gitlab-org/gitlab-ce/issues/48293

**Comment by Gambler13** [comment]
Seems to be a problem with GitLab. Perhaps multiple servers behind a load balancer without syncing the JWKS.

https://gitlab.com/gitlab-org/gitlab-ce/issues/48963
