### ISSUE TITLE
The code unnecessarily set client_secret 

### ISSUE THREAD

**Issue by SongGithub** [coreos/go-oidc#181]
## direct consequence of the problem:
I was trying to integrate [Keycloak](https://github.com/keycloak/keycloak-gatekeeper) with Microsofts' implementation of OIDC, and getting 403 error that is ```"keycloak-gatekeeper/handlers.go:121","msg":"unable to exchange code for access token","error":"invalid_request: MSIS9631: Received invalid OAuth request. Multiple client authentication methods were attempted.```

That was because MS's OIDC protocol mandates [The client MUST NOT use more than one authentication method in each request](https://tools.ietf.org/html/rfc6749#section-2.3), and Keycloak was sending auth-code to exchange for `access token` at ADFS server's token endpoint, with both client-authentication methods: `basic` and `post`, which violates the above mentioned mandate. 

I read through Keycloak's code and trace it down to this repo which referred as a go-library. And I found out that when using Keycloak's default auth method `basic auth`, it should only set security header, not to have client_secret in the HTTP POST body as well. Unfortunately, there is a line of unnecessary code that set client_secret in a variable that end up in HTTP POST body before the code could determine which auth method was the calling RP client set to using. 

## cause in the code
[This line of code](https://github.com/coreos/go-oidc/blob/e860bd55bfa7d7cb35d30d26a167982584f616b0/oauth2/oauth2.go#L260) is totally unnecessary, as the client_secret will be set in [downstream method](https://github.com/coreos/go-oidc/blob/e860bd55bfa7d7cb35d30d26a167982584f616b0/oauth2/oauth2.go#L185) only when it is using method AuthMethodClientSecretPost. 

In current setup, the other auth method AuthMethodClientSecretBasic will have client_secret in the Body which is not tolerated by MS's OIDC (ADFS/OIDC/Token-endpoint)

**Comment by SongGithub** [comment]
I can help to make a PR to fix the problem. please let me know. thanks.

**Comment by ericchiang** [comment]
The code you're referring is the v1 branch, which was mark deprecated a year ago. The v2 branch uses golang.org/x/oauth2. Keycloak needs to switch.

**Comment by SongGithub** [comment]
indeed. thanks for the insight!

**Comment by abstractj** [comment]
@SongGithub this is being tracked here https://issues.jboss.org/browse/KEYCLOAK-7265 an planned for further releases. Go-oidc changed a lot the codebase, so we need to make sure that everything is in place.
