### ISSUE TITLE
Unnecessary client secret setting

### ISSUE THREAD

**Issue by SongGithub** [coreos/go-oidc#182]
## direct consequence of the problem:
I was trying to integrate [Keycloak](https://github.com/keycloak/keycloak-gatekeeper) with Microsofts' implementation of OIDC, and getting 403 error that is ```"keycloak-gatekeeper/handlers.go:121","msg":"unable to exchange code for access token","error":"invalid_request: MSIS9631: Received invalid OAuth request. Multiple client authentication methods were attempted.```

The reason for above error was due to both auth methods `post` & `basic auth` were used in the same request sent out to the OP (ADFS/OIDC/token-endpoint)

## cause in the code
directly cause for the error was due to a line of [unnecessary client_secret setting](https://github.com/coreos/go-oidc/blob/e860bd55bfa7d7cb35d30d26a167982584f616b0/oauth2/oauth2.go#L260). it is unnecessary because it will/should be set [only when auth method is `post`](https://github.com/coreos/go-oidc/blob/e860bd55bfa7d7cb35d30d26a167982584f616b0/oauth2/oauth2.go#L185). Setting it too early in variable `v` will cause an extra content client_secret in request body regardless of selected auth method, which will not be tolerated by [MS's ADFS/OIDC](https://tools.ietf.org/html/rfc6749#section-2.3)

**Comment by aklinkert** [comment]
@SongGithub I ran into this today with OneLogin.com. What was the reason for you to close this issue?

*Background:*
As far as I understand the code I would need to configure the OIDC provider to accept the secret as body parameter to get this one working, right? Unfortunately I am trying to use the keycloak/keycloak-gatekeeper project which is setting the `AuthMethod` to basic per default right now and isn't changeable too ( https://github.com/keycloak/keycloak-gatekeeper/blob/fa53727277a1f931498fddb998bb54149845bf23/oauth.go#L39). So I guess I am stuck with this unless this isn't fixed. 😅 

Oh damn, it's a duplicate, I see. For all of you coming from Google: 👉  #181

**Comment by ghost** [comment]
Also experiencing this issue with Okta as my OIDC provider. Using go-oidc via keycloak-gatekeeper and `RequestToken` is setting >1 client credentials. Okta returns the following error:

```
invalid_request: Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body.
``` 

(see [Okta API /token docs](https://developer.okta.com/docs/api/resources/oidc#token))

**Comment by SongGithub** [comment]
That was right, @apinnecke , in [another issue](https://github.com/coreos/go-oidc/issues/181), it has been confirmed that the buggy version of `KeyCloak-gatekeeper` has been using deprecated go-oidc v1. The Keycloak project has got a plan to upgrade it to use go-oidc client v2, and I can see it is progressing in `development` branch. 

For the time being, I would just use an open source project `dex` to abstract the Microsoft AD server. Dex talks to AD with trusty SAML, while Dex plays role of IdP when talking to apps need authentication.

**Comment by chickenriggies** [comment]
Any updates or guidance on this?

**Comment by ericchiang** [comment]
@hb3b see https://github.com/coreos/go-oidc/issues/181#issuecomment-431870483
