### ISSUE TITLE
Skip issuer URL check

### ISSUE THREAD

**Issue by pankrator** [coreos/go-oidc#183]
Would it make sense to add possibility to skip the Issuer URL [check][2], like the [client id][1]?
We have a use case where the Authorization server issues tokens with different issuer urls.

[1]: https://github.com/coreos/go-oidc/blob/v2/verify.go#L86
[2]: https://github.com/coreos/go-oidc/blob/v2/verify.go#L234-L243

**Comment by ericchiang** [comment]
dup of https://github.com/coreos/go-oidc/issues/159 and several other issues

tl;dr - no
