### ISSUE TITLE
Please give me admin rights to go-oidc

### ISSUE THREAD

**Issue by ericchiang** [coreos/go-oidc#185]
I still plan on maintaining this package but am no longer in the coreos org. Can someone give me admin rights?

Tagging a random assortment of people who might be able to help.

cc @kbrwn
cc @philips 
cc @brancz

**Comment by philips** [comment]
will do.

Please fix https://github.com/coreos/go-oidc/issues/186 :)

**Comment by philips** [comment]
invite sent @ericchiang

**Comment by ericchiang** [comment]
Thanks Brandon!
