### ISSUE TITLE
OIDC requests ignore proxy server

### ISSUE THREAD

**Issue by lanoxx** [coreos/go-oidc#191]
It seems that the OIDC request that are being invoked from this library ignore if a proxy server has been configured on the users host or if the caller of this library is using a library such as `go-ieproxy` to configure a proxy.

The problem seems to lie here: https://github.com/coreos/go-oidc/blob/66476e0267012774b2f9767d2d37a317d1f1aac3/oidc.go#L61

The client that is configured there does not use the `http.DefaultTransport` which would normally include the proxy. I am not sure how the `oauth2.HTTPClient` is being constructed. But a solution to this problem is to assign an `httpDefaultTransport` to `client.Transport`.

Any chance you could fix this problem?

**Comment by mikedanese** [comment]
Whoever is calling this library controls what client is set at the line you reference. You can change the context's http.Client using:

https://godoc.org/github.com/coreos/go-oidc#ClientContext

This library will use any client set in the context, and it will fallback to http.DefaultClient (which uses http.DefaultTransport).

**Comment by lanoxx** [comment]
Thanks for the information. I am closing this ticket. Sorry for the noise.
