### ISSUE TITLE
how to refresh id token using refresh token

### ISSUE THREAD

**Issue by alok87** [coreos/go-oidc#199]
Is there an example in which we use the refresh id token using refresh token when the id token has expired?

**Comment by mikedanese** [comment]
This package provides oidc discovery utilities that are not provided by golang.org/x/oauth2. Follow the example in the readme:

```golang
ctx := context.Background()
provider, err := oidc.NewProvider(ctx, "https://accounts.google.com")
if err != nil {
    // handle error
}

// Configure an OpenID Connect aware OAuth2 client.
oauth2Config := oauth2.Config{
    ClientID:     clientID,
    ClientSecret: clientSecret,
    RedirectURL:  redirectURL,

    // Discovery returns the OAuth2 endpoints.
    Endpoint: provider.Endpoint(),

    // "openid" is a required scope for OpenID Connect flows.
    Scopes: []string{oidc.ScopeOpenID, "profile", "email"},
}
```

Then you want to use this:

https://godoc.org/golang.org/x/oauth2#Config.TokenSource

e.g.

```go
ts := oauth2Config.TokenSource(ctx, &oauth2.Token{RefreshToken: secretStuff})
tok, err := ts.Token()
```

**Comment by alok87** [comment]
thank you

**Comment by smartaquarius10** [comment]
@mikedanese , Hello,
Could you please confirm one thing here. Once we have this refresh token do we have to manually send a refresh token request. Else do you have any details or example available to elaborate it a little more please. I'm super stuck at refreshing token in case of OIDC authorization flow.
