### ISSUE TITLE
Difficulty in Mock Test

### ISSUE THREAD

**Issue by leosabbir** [coreos/go-oidc#201]
Having **oidc.UserInfo** and **oidc.Provider** struct is making my life difficult to mock them for testing.

**Comment by ericchiang** [comment]
NewVerifier and KeySet are exported to allow mocking for testing

https://godoc.org/github.com/coreos/go-oidc#NewVerifier
https://godoc.org/github.com/coreos/go-oidc#KeySet

Do you have an example of what kind of program you're trying to test?

**Comment by leosabbir** [comment]
lets assume following code snippet:

```
// userInfo retrieves user information from the accessToken
func userInfo(ctx context.Context, accessToken string) (map[string]interface{}, error) {
	token := &oauth2.Token{
		AccessToken: accessToken,
	}
	userInfo, err := provider.UserInfo(ctx, oauth2.StaticTokenSource(token))
	if err != nil {
		log.Println("UserInfo: Error retrieving userInfo: ", err)
		return nil, err
	}

        ......
}
```

**provider** is an instance of oidc.Provider
`userInfo, err := provider.UserInfo(ctx, oauth2.StaticTokenSource(token))`

I am trying to write unit test for userInfo() and I need to mock this "**provider"**. Since it is **struct**, I am unable to mock it. I am able to mock only the interfaces.

Similar is the case for 1. oidc.UserInfo, 2. oidc.IDToken. I cannot mock them.

**Comment by leosabbir** [comment]
For now I have fixed it by creating intermediate interfaces. But I have to do this just for creating unit tests and it doesn't sound right.

**Comment by mikedanese** [comment]
The go idiom is that packages should export concrete types. Interfaces should be defined when and where multiple implementations are required (e.g. struct oidc.Provider, struct fakeProvider, interface provider in your case).

https://github.com/golang/go/wiki/CodeReviewComments#interfaces
