### ISSUE TITLE
Consider a flag in the config to disable provider/issuer checking

### ISSUE THREAD

**Issue by lsoares** [coreos/go-oidc#204]
Regarding [a validation the library is doing](https://github.com/coreos/go-oidc/blob/8ae1da518bd4d9d5a5909090a184af30f336436d/oidc.go#L123) we'd need a way to turn it off.
We understand it makes sense in most cases, but given our needs, it would be helpful to be able to turn it off through a flag (that by default is off).

We can do a PR if this makes sense to you. What's your opinion?

**Comment by mikedanese** [comment]
Why do you need this? See also:

https://github.com/coreos/go-oidc/blob/274971e2c94cd6fb17614979e2899edbc81af146/verify.go#L97

**Comment by lsoares** [comment]
We need it because the requested provider config comes from:
"https://grp-de-qa.COMPANY.com/.well-known/openid-configuration"
but the issuer in the JSON is:
"https://grp-qa.COMPANY.com"

I also agree that [it should follow the standard](https://security.stackexchange.com/questions/212724/oidc-should-the-provider-have-the-same-address-as-the-issuer) but why they did it is out of our control. Maybe the host being the same could be an alternative validation.

But for now, that flag seems to solve our issue. Do you plan it to merge to `master`? If so, when? Thank you very much!

**Comment by lsoares** [comment]
We need it because the requested provider config comes from:
"https://app-locale-env.COMPANY.com/.well-known/openid-configuration"
but the issuer in the JSON is:
"https://app-env.COMPANY.com"

I also agree that it should [follow the standard](https://security.stackexchange.com/questions/212724/oidc-should-the-provider-have-the-same-address-as-the-issuer) but why they did it is out of our control. Maybe the host being the same could be an alternative validation.

But for now, that flag seems to solve our issue. Do you plan it to merge to master? If so, when? Thank you very much!

**Comment by ericchiang** [comment]
Which provider is this? Can you open an issue with them instead? I'd like to not add flags for providers that go off spec, and this particular option would make it unclear which issuer to user for ID token validation.

Plus, you can already work around this today:

```go
resp, err := http.Get("https://app-locale-env.COMPANY.com/.well-known/openid-configuration")
if err != nil {
    // ...
}
defer resp.Body.Close()
var metadata struct {
    AuthEndpoint  string `json:"authorization_endpoint"`
    TokenEndpoint string `json:"token_endpoint"`
    JWKSURL       string `json:"jwks_uri"`
}
if err := json.NewDecoder(resp.Body).Decode(&metadata); err != nil {
    // ...
}
config := &oidc.Config{ClientID: "my-client-id"}
keySet := oidc.NewRemoteKeySet(ctx, metadata.JWKSURL)
verifier := oidc.NewVerifier("https://app-env.COMPANY.com", keySet, config)
```

**Comment by ericchiang** [comment]
> But for now, that flag seems to solve our issue. Do you plan it to merge to master? If so, when? Thank you very much!

It's already on the v2 branch (we don't develop on master), but it's only for id_token validation, not discovery.

**Comment by lsoares** [comment]
OK regarding the branch, it's an issue with Go Modules that defaults to `master`, so I have to find a way to work around it.
Anyway, as you said that flag only works for verification; not initialization.
It's an internal provider of my company so I can't give more details. But then I went and found that Microsoft also does this right? Examples:
https://login.microsoftonline.com/contoso.onmicrosoft.com/v2.0/.well-known/openid-configuration
https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

**Comment by ericchiang** [comment]
Per the Go Modules question https://stackoverflow.com/a/53682399

The Azure examples are a perfect reason why I don't want to add an option. The issuer isn't:

```
https://login.microsoftonline.com/contoso.onmicrosoft.com/v2.0/
```

It's supposed to be:

```
https://login.microsoftonline.com/31537af4-6d77-4bb9-a681-d2394888ea26/v2.0
```

**Comment by lsoares** [comment]
OK I understand why you wouldn't want to support these Azure examples. Thanks for the help!

**Comment by MaikuMori** [comment]
Isn't Live ID also perfect example why it should be allowed?

The correct discovery URL for any live sign in is:
> https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

But in the response they return:

> issuer: "https://login.microsoftonline.com/{tenantid}/v2.0"

Obviously Microsoft is wrong here, but they're also relatively big provider and the only way to work around it is by re-implementing the function w/o the check.

I do agree that flag is rather nasty hack and pollutes the API. How about another relaxed New function?

EDIT:
By forcing users to re-implement this part themselves there is a chance that they will introduce a bug.

**Comment by ericchiang** [comment]
@MaikuMori you're supposed to replace `{tenantid}` with your Tenant ID.

Let me open an issue to document this. It's one of our most common questions.
