### ISSUE TITLE
Add userinfo_endpoint to Provider struct as a shortcut for Caims()

### ISSUE THREAD

**Issue by joshua-rutherford** [coreos/go-oidc#206]
The specification allows for the UserInfo endpoint to return signed and/or encrypted responses based upon client configuration (https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse).  At present, only a plain JSON object is supported.  Is there an interest in supporting this functionality in some way?  

Perhaps this could be supported in a simple way by allowing the caller to implement the processing of the returned body.  See https://github.com/coreos/go-oidc/pull/205.

**Comment by ericchiang** [comment]
Instead of #205 I'd prefer we either:
1) do the signature verification/decryption ourselves or
2) do nothing and let users hit the user endpoint themselves, e.g.

```go
p, err := oidc.NewProvider(ctx, "...")
if err != nil {
    // ...
}
var claims struct {
    UserInfoEndpoint string `json:"userinfo_endpoint"`
}
if err := p.Claims(&claims); err != nil {
    // ...
}
req, err := http.NewRequest("GET", claims.UserInfoEndpoint, nil)
if err != nil {
    // ...
}
req.Header.Set("Authorization", "Bearer "+token)
// do and handle request yourself
```

**Comment by joshua-rutherford** [comment]
The first option won't really work for my use case as I want access to the signed token.  However, the second is workable.  Out of curiosity, any desire to export `providerJSON`? It's just the definition of the bits of `.well-known/openid-configuration` we are interested in.  Clearly, that's not a blocker to your approach above but might be cleaner than having people redefine the discovery struct.

**Comment by ericchiang** [comment]
They've been private because it's good to default fields to unexported, but
I'd be fine adding a subset of the fields to the Provider struct. Auth,
token, and userinfo endpoints would be a good place to start.

Probably don't want to add optional metadata fields especially if they
require validation. We used to try to parse every field and found a few
providers would return strings instead of arrays and stuff like that.

**Comment by ericchiang** [comment]
Updated the title to reflect this feature request. Feel free to send a PR :)
