### ISSUE TITLE
Allow user to specify issuer uri and well known config uri independently

### ISSUE THREAD

**Issue by ardove** [coreos/go-oidc#213]
Currently, the library just uses the issuer string and tacks on "/.well-known/openid-configuration" to the end of it. This is problematic when the well known configuration api isn't directly underneath the issuer location. 

An alternative to allowing someone to provide whatever they want as the issuer uri and the well known configuration uri, would be to just validate that the hosts are the same (instead of the full uri passed in as issuer).  

Here's an example:
Well known configuration uri: http://my.identity-provider.com/api/v1/oauth2/.well-known/openid-configuration
Issuer returned by the identity provider: http://my.identity-provider.com/

If I specify the issuer via the NewProvider function here https://github.com/coreos/go-oidc/blob/v2/oidc.go#L96 as "http://my.identity-provider.com/api/v1/oauth2", and "http://my.identity-provider.com/api/v1/oauth2/.well-known/openid-configuration" returns "http://my.identity-provider.com/" as the issuer, the check for provider matching at https://github.com/coreos/go-oidc/blob/v2/oidc.go#L124 fails because "http://my.identity-provider.com/api/v1/oauth2" != "http://my.identity-provider.com/".

You might say that I should change the api so that the well-known configuration uri lives at the root of the issuer uri, but unfortunately that presents a few limitations:
1) It doesn't allow me to version my well known configuration when I have multiple identity providers
2) I may not have control over the identity provider, and as such, I can't use your library

**Comment by ericchiang** [comment]
This validation part of the spec :)

> OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string /.well-known/openid-configuration to the Issuer.

https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig

If you'd like to host alternative URLs for your well-known endpoint that's fine, but it's off spec and clients aren't obliged to implement the non-standard scheme.

**Comment by ardove** [comment]
You're right. Due to circumstances, we'll need to fork your repository and make the change so we can use the updated artifact internally. 

Which branch is currently deployed and available via https://www.npmjs.com/?

**Comment by ericchiang** [comment]
Okay sounds like this issue can be closed out :)

This is a Go package, so it's not going to be available via NPM. You'll want to look at "go get" https://golang.org/cmd/go/#hdr-Add_dependencies_to_current_module_and_install_them

**Comment by ardove** [comment]
Right. Sorry, mixed contexts. 

In any case, which branch represents the version currently available as a public package?

**Comment by ericchiang** [comment]
The default branch is v2
