### ISSUE TITLE
Azure custom signing keys

### ISSUE THREAD

**Issue by stuart-c** [coreos/go-oidc#215]
Azure will in certain situations use custom signing keys on a per-application basis. To fetch these custom keys this is implemented by adding ?appid={app-id} to the end of the discovery URL.

As this is currently not possible via go-oidc any JWT validation using a custom signing key will fail due to the inability to find the key.

Azure documention: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#fetch-the-openid-connect-metadata-document

Related issue: https://github.com/hashicorp/vault-plugin-auth-jwt/issues/75

**Comment by ericchiang** [comment]
Does providing your own RemoteKeySet work?

https://godoc.org/github.com/coreos/go-oidc#NewRemoteKeySet

E.g. 

```go
keys := oidc.NewRemoteKeySet(ctx, "https://login.microsoftonline.com/foo/discovery/v2.0/keys?appid=6731de76-14a6-49ae-97bc-6eba6914391e")

cfg := &oidc.Config{ClientID: clientID}
verifier := oidc.NewVerifier("https://login.microsoftonline.com/foo", keys, cfg)
```

**Comment by ericchiang** [comment]
Closing for now. please give that a try.
