### ISSUE TITLE
The issuer should not be known by the client.  Only authority is needed.

### ISSUE THREAD

**Issue by ghstahl** [coreos/go-oidc#219]
```
provider, err := oidc.NewProvider(ctx, "https://localhost:6001")
....
if p.Issuer != issuer {
		return nil, fmt.Errorf("oidc: issuer did not match the issuer returned by provider, expected %q got %q", issuer, p.Issuer)
	}
```

1. The spec does not state that the "Authority" == issuer, which this code assumes.  
2. The issuer can point to anything and does not need to be in the same domain.  i.e. Authority = https://a.b.com, issuer = https://a.cat.com 

The issuer returned by 

> /.well-known/openid-configuration

 needs only to match the iss in the JWT tokens that follow.    The only knowledge the client should have is "authority".  

the call should be;
```
authority := "https://localhost:6001"
issuer := "<you will be told this by openid-configuration>"
provider, err := oidc.NewProvider(ctx,authority)  
```

Using this code will break in the field if an IDP like google decides to change the issuer, which by spec they can.

**Comment by ericchiang** [comment]
Dup of the following issues?

https://github.com/coreos/go-oidc/issues/213
https://github.com/coreos/go-oidc/issues/204
https://github.com/coreos/go-oidc/issues/203
https://github.com/coreos/go-oidc/issues/183
https://github.com/coreos/go-oidc/issues/159

I don't really see anything new in this issue. The spec clearly states that when doing http discovery, the "iss" MUST identically match the URL provided.

What provider or setup are you having issues with?

**Comment by mikedanese** [comment]
To prevent impersonation attack:

> RPs MUST ensure that the Issuer URL they are using for the Configuration Request exactly matches the value of the issuer Claim in the OP Metadata document received by the RP and that this also exactly matches the iss Claim value in ID Tokens that are supposed to be from that Issuer.

https://openid.net/specs/openid-connect-discovery-1_0.html#Impersonation

**Comment by ghstahl** [comment]
**To prevent impersonation attack**: I cover this on my exposed APIS, I don't need to cover it when a client obtains an access_token.

The spec talks about Validation, and not discovery rules.

4.3.  OpenID Provider Configuration Validation
If any of the validation procedures defined in this specification fail, any operations requiring the information that failed to correctly validate MUST be aborted and the information that failed to validate MUST NOT be used.

The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer.

I have an API, that rigidly follows the above
assume authority: **https://accounts.google.com**
[accounts.google.com/.well-known/openid-configuration](https://accounts.google.com/.well-known/openid-configuration)
1. The issuer in openid-configuration MUST match the authority when I validate that bearer token

The whole thing here for me is the validation of the bearer token.

I have a client, that must be considered compromised, hence I don't really care how it got its access_token.  I need to make sure my API is secured.

In the case of the client, I am actually doing something that is legitimate but could be seen as something an attacker would do.

The authority I give the client is a little interesting.
Clients Authority: **https://localhost:6001**
[Client Sees This openid-configuration](https://gist.github.com/ghstahl/7ea35ae28fec7eac49920833798d2e7f)

If you see that config, the authority is NOT the same as the issuer, but in this case it is not a problem.
The mitigation is that the api isn't using **https://localhost:6001** as its authority, it is using **https://accounts.google.com**.  As I said above, now the rules get ridged.

If you want to default to checking the issuer, then fine, but at least let me opt-out of it.  There are legit cases where issuer != authority is OK.

My client (some console app) is coded up to login to an OIDC idp, which in my case is really an orchestrator pretending to be an OIDC idp.    In the end, a correct access_token is given out, and correctly validated at the secured endpoint.

**Comment by mikedanese** [comment]
oidc.NewProvider builds a verifier using OIDC discovery and provides utilities for accessing discovered metadata. I'm not sure it provides value without discovery. Why not use [oidc.NewVerifier](https://godoc.org/github.com/coreos/go-oidc#NewVerifier) with [oidc.NewRemoteKeySet](https://godoc.org/github.com/coreos/go-oidc#NewRemoteKeySet)?

**Comment by ghstahl** [comment]
I will give that a go.  BTW: is there a plan to add support for Authorization Code Flow with PKCE for Native Apps?

**Comment by ericchiang** [comment]
@ghstahl from what I can tell, PKCE is an addition to OAuth2, not OpenID Connect. I don't expect this package to add PKCE support though it is mentioned in golang.org/x/oauth2

https://godoc.org/golang.org/x/oauth2#Config.AuthCodeURL
https://godoc.org/golang.org/x/oauth2#Config.Exchange

**Comment by ericchiang** [comment]
Going to close this as a dup of the issues listed above. Again, the spec says we MUST perform this validation, it's regularly caught mis-configuration issues (#212), and it sounds like you're intentionally doing something the spec disallows where we provide the workarounds @mikedanese mentioned.
