### ISSUE TITLE
support identity providers with bare issuer hostname

### ISSUE THREAD

**Issue by jcarrothers** [coreos/go-oidc#221]
I'm dealing with a particularly stubborn OIDC provider which insists on having a bare hostname (without the `https://` scheme), and the issuer.  Based on my research of the OIDC spec this is odd, but not necessarily outside of the spec documents due to the normalization steps in Section 2.1.2: https://openid.net/specs/openid-connect-discovery-1_0.html#NormalizationSteps

In this case, the provider is setting the issuer field of `/.well-known/openid-configuration` to the bare hostname, and doing the same in the `iss` field of the generated JWTs.  I have already done some basic testing on a patch to support this oddity, but I wanted to get some input on this prior to opening a pull request.

**Comment by mikedanese** [comment]
That section applies to webfinger discovery of the issuer URL of an OIDC provider for a given subject. The issuer URL always needs to have an https scheme:

> An Issuer Identifier is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components.

With one exception made for the Google issuer:

https://openid.net/specs/openid-connect-core-1_0.html#GoogleIss

**Comment by jcarrothers** [comment]
If it's possible to make an exception for an inconsistent issuer, would it not be acceptable to support a general case of a somewhat misconfigured issuer?
(Edit: I just realized that the google exception is even in the spec document, that is... interesting.)

To get some code in here, these are the two options I was thinking of:
https://github.com/coreos/go-oidc/compare/v2...jcarrothers:supportBareIssuer?expand=1
https://github.com/coreos/go-oidc/compare/v2...jcarrothers:supportBareIssuerAlt?expand=1

The first has the advantage of being a little more flexible in the case of trying to handle an issuer that is miscofigured in this way, but the second is a minimal code change that would work around this particular issue.

I would agree that a correct reading of the spec indicates that the issuer should never be without the scheme, but given that OIDC prohibits any protocol except https, the mistake is somewhat understandable.  Not to mention, once a setup has made this mistake, it may be next to impossible to correct, if a number of service providers, that are willing to be flexible in this manner, are already connected to the Identity Provider.

**Comment by ericchiang** [comment]
You can work around this by doing your own discovery and calling NewRemoteKeySet and NewVerifier:
https://godoc.org/github.com/coreos/go-oidc#NewRemoteKeySet
https://godoc.org/github.com/coreos/go-oidc#NewVerifier

What provider is this? Can you open a ticket against them instead?

We've been against these kind of changes in the past:
#219 
#213
#204
#203
#183
#159

**Comment by ericchiang** [comment]
Friendly ping
