### ISSUE TITLE
Support OPs which require Authorization header against JWK URL

### ISSUE THREAD

**Issue by hashedhyphen** [coreos/go-oidc#222]
Example OP: Oracle Identity Cloud Service (IDCS)

IDCS provides `jwk_uri`, which requires Authorization header containing Bearer access token.
i.e.) https://docs.oracle.com/en/cloud/paas/identity-cloud/17.3.6/rest-api/op-admin-v1-SigningCert-jwk-get.html

AFAICS `go-oidc` doesn't send Authorization header when retrieving JWK currently.

Is this intentional design or one just not implemented now?

**Comment by ericchiang** [comment]
Sorry, I was on vacation last week.

This is the first time I've heard of a service requiring an Authorization header. This does seem like something that we should be configurable. You can accomplish this today with a custom http.Client and the golang.org/x/oauth2 package:

```go
// do discovery normally
provider, err := oidc.NewProvider(ctx, issuerURL)
if err != nil {
    // handle error
}
var claims struct {
    JWKURI string `json:"jwk_uri"`
}
if err := provider.Claims(&claims); err != nil {
    // handle error
}

// Create a custom remote key set, providing a client that sends the bearer token
client := &http.Client{
    Transport: &oauth2.Transport{
        Source: oauth2.StaticTokenSource(&oauth2.Token{
            AccessToken: myBearerToken,
        }),
    },
}
remoteKeySetCtx := oidc.ClientContext(ctx, client)
keySet := oidc.NewRemoteKeySet(remoteKeySetCtx, claims.JWKURI)

// Create an ID Token verifier from the key set
config := &oidc.Config{
    ClientID: myClientID,
}
verifier := oidc.NewVerifier(issuerURL, keySet, config)
```

I'm trying to figure out if there's a better API for this?

**Comment by hashedhyphen** [comment]
I see. That workaround seems reasonable :tea:

By the way, some of my investigation found Oracle IDCS had an option to disable Authorization header checking against jwk_url.

Moreover, I'm not sure what the checking is aiming for and what a value should be used for the Bearer access token...

So the feature request of this PR is not needed for now, so I'll close this.
