### ISSUE TITLE
Provide StandardClaims struct in the library

### ISSUE THREAD

**Issue by labkode** [coreos/go-oidc#224]
Hi,

I think it could be handy to provide a public exported struct `StandardClaims` in the library as per
https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims.

If it makes sense I can make a PR.

Thanks!

**Comment by ericchiang** [comment]
Hey @labkode,

My experience with providers is that standard claims aren't actually that standard. I've never seen one that returns the users "gender" for example.

I also actually like users defining their own structs for the Claims method. It demonstrates that if they want a non-standard claim, they can just add it to their own struct.

I'm fine continuing to expose required claims to the IDToken struct itself, but I don't see a huge win out of adding a StandardClaims helper to this package.

**Comment by labkode** [comment]
@ericchiang thanks, fair enough!
