### ISSUE TITLE
Cannot import Go module

### ISSUE THREAD

**Issue by misberner** [coreos/go-oidc#230]
Super happy to see Go modules support came to this project with the most recent release! Unfortunately, it looks like the major version of 2 requires the module to declare its path as `github.com/coreos/go-oidc/v2`, as I'm seeing:
```
require github.com/coreos/go-oidc: version "v2.2.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

Happy to send out a PR, but wondered whether that should just migrate all package names to `.../v2`, or if this needs to be bumped to `v3` as the package name change itself would be backwards-incompatible.

NOTE: I saw that there was some discussion around possibly making this a `/v2` module on the PR, but I think the way Go modules works, this is actually non-optional. Even if I append a `+incompatible` I get this error:
```
verifying github.com/coreos/go-oidc@v2.2.0+incompatible/go.mod: github.com/coreos/go-oidc@v2.2.0+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/coreos/go-oidc@v2.2.0+incompatible: 410 Gone
```

**Comment by ericchiang** [comment]
Thanks for opening this issue. I'm going to go ahead an revert the go.mod for v2 and we can discuss a v3 :)

**Comment by ericchiang** [comment]
I field #232 for some thoughts on a v3
