### ISSUE TITLE
Issuer check in oidc.NewProvider - strict issuer checking seems unnecessary

### ISSUE THREAD

**Issue by bandesz** [coreos/go-oidc#238]
## What

When a new provider instance is created, it goes to the discovery url (`/.well-known/openid-configuration`) and checks whether the issuer parameter matches exactly the issuer variable value.

NewProvider throws an error if you've included a trailing slash at the end of the issuer, but the discovery url returns the value without it and vice-versa. It seems to me this strict check has no useful purpose and makes misconfiguration issues easier.

I propose to ignore trailing slash differences in NewProvider, to have a better user experience.

As a previous issue about this was closed (https://github.com/coreos/go-oidc/issues/66) I wanted to ask first whether you would be open about receiving a change PR for this.

**Comment by ericchiang** [comment]
#66 was fixed by https://github.com/coreos/go-oidc/pull/67

If you provide a trailing slash, this package follows the spec :)

https://github.com/coreos/go-oidc/blob/8d771559cf6e5111c9b9159810d0e4538e7cdc82/oidc.go#L114

> If the Issuer value contains a path component, any terminating / MUST be removed before appending /.well-known/openid-configuration.

https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest

**Comment by bandesz** [comment]
@ericchiang that is not the problem, this is:
https://github.com/coreos/go-oidc/blob/8d771559cf6e5111c9b9159810d0e4538e7cdc82/oidc.go#L140

Depending on whether I pass the value of `issuer` with or without trailing slash, NewProvider will throw an error.

**Comment by bandesz** [comment]
Basically that line should be:

```golang
if strings.TrimSuffix(p.Issuer, "/") != strings.TrimSuffix(issuer, "/")
```

**Comment by bandesz** [comment]
I've opened a PR for this: https://github.com/coreos/go-oidc/pull/239

**Comment by ericchiang** [comment]
Hey sorry for the delayed response. Things are getting busy at work :)

There's been a lot of requests to relax Issuer validation. And from a maintenance perspective, it's been waaay simpler to follow the spec than to be lax.

Being lax also has its downside that other libraries won't interact well with this package. For example, Kubernetes does similar checks, and you'd get weird mismatches if we accepted #239

https://github.com/kubernetes/apiserver/blob/822585c65b3829cc20fbcbe76481f7413d5fd98e/plugin/pkg/authenticator/token/oidc/oidc.go#L356

Overall I think it's best to stick to the spec and improve documentation and error messages to help users.

**Comment by bandesz** [comment]
I see what you mean and I understand why you shouldn't accept this specific change.

We are creating a product where our users will set the issuer URL. As you can understand, this is not a great user experience still, that they have to care about a trailing slash in their configs.

As a workaround, I can go to the discovery URL myself, get the issuer and initialise the oidc library with that exact issuer string, but that means I will fetch the discovery URL twice.

**Comment by ericchiang** [comment]
> As a workaround, I can go to the discovery URL myself, get the issuer and initialise the oidc library with that exact issuer string, but that means I will fetch the discovery URL twice.

If you're doing discovery yourself, you can build a verifier without calling NewProvider and making a redundant request :)

https://godoc.org/github.com/coreos/go-oidc#NewRemoteKeySet
https://godoc.org/github.com/coreos/go-oidc#NewVerifier

Going to close this issue for the reasons outlined above. Let me know if there's anything else I can help out with.
