### ISSUE TITLE
Issuer Name Mismatch

### ISSUE THREAD

**Issue by western24** [coreos/go-oidc#240]
Hi,
I'm trying to use oauth2_proxy with Oracle Identity Cloud Service.  The following parameters are added in the configuration file as Open ID Connect. But  I'm faced with an error that the issuer didn't match. Probably, issuer value returned by Oracle IDCS is different from your expectations.  Can I avoid this error?

client_id = "xxxxxx"
client_secret = "xxxxxxx"
provider = "oidc"
oidc_issuer_url ="https://idcs-fd65079a19ab43ab808d264c927d3401.identity.oraclecloud.com"

sudo  /usr/local/sbin/oauth2_proxy -config /etc/oauth2_proxy.cfg
[2020/03/16 16:09:19] [main.go:160] oidc: issuer did not match the issuer returned by provider, expected "https://idcs-fd65079a19ab43ab808d264c927d3401.identity.oraclecloud.com" got "https://identity.oraclecloud.com/"

- Version used:
v5.0.0.

I've filed it here as well.
https://github.com/pusher/oauth2_proxy/issues/449

**Comment by bandesz** [comment]
Sadly the discovery endpoint does not conform to the OpenID Connect Discovery specification:

> The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer.

https://openid.net/specs/openid-connect-discovery-1_0.html#rfc.section.4.3

**Comment by western24** [comment]
Thank you for your comment. I can understand your policy.
FYI, the issuer value of current Oracle IDCS cannot be configurable. but I've heard the upcoming Oracle IDCS can be changed it by a user.
