### ISSUE TITLE
access token verification without at_hash?

### ISSUE THREAD

**Issue by dalu** [coreos/go-oidc#241]
In this package you're using the `at_hash` claim to verify that the access token is authentic.

Is there a way to do it without the `at_hash`?
There does not seem to be a way to access the introspection endpoint with this package.

Is there a alternative way?

**Comment by ericchiang** [comment]
at_hash is used to tie the ID token to the access token, which I believe adds some extra verification during the Implicit Flow where these tokens are returned directly in a browser redirect.

When you use Go's oauth2 package, you're using the Authorization Code Flow where you connect directly to the provider (e.g. Google) which issues you an ID token and an access token. For that case, you can generally trust TLS.

Either way, the API depends on at_hash, so you won't be able to call `(i *IDToken) VerifyAccessToken` if your ID token doesn't have that claim. But omitting that should be fine for a most threat models.

**Comment by dalu** [comment]
apparently in the hybrid flow `code id_token token` the `at_hash` claim is mandatory.

The thing is, if I want to verify an access token that was issued to a (single page app) client (same client id) using code+pkce I'm not able to verify its authenticity with this library, because the at_hash claim is missing from the id token (only mandatory in implicit flow) and this library only does access token validation using the `at_hash` claim.
