### ISSUE TITLE
Migration from v1 to v2

### ISSUE THREAD

**Issue by SvenDowideit** [coreos/go-oidc#242]
I just had an issue with claim verification failing in keycloak, and make a hack for it - see https://github.com/keycloak/keycloak-gatekeeper/issues/514

keycloak-gatekeeper currently seems to use go-oidc v1 - is this something that needs changing urgently, or is it safe to not rush upgrading to v2?

**Comment by ericchiang** [comment]
The v1 branch has been depreciated for over three years https://github.com/coreos/go-oidc/commit/52557de1264893b367d0f318f8fce7d5ec4c400b

There's been no development on that branch, and I wouldn't be surprised if it has security issues :) this has been noted in the past. Keycloak needs to update.

**Comment by SvenDowideit** [comment]
Thanks heaps, I assumed as much, but thought it worth confirming
