### ISSUE TITLE
Got error message "failed to verify signature: failed to verify id token signature" when remote provider server is restarted

### ISSUE THREAD

**Issue by fezho** [coreos/go-oidc#243]
I use dex as auth provider, and verify the id token by calling `verifier.Verify`. Everything works well. However, if the dex is restarted, then the token can not be verified, and got "failed to verify signature: failed to verify id token signature". 

This is because dex changes its JWKS signing keys after restarted, so remoteKeySet's verify throws error. Can the `go-oidc` library adds some retry logic to refresh the signing keys.

**Comment by ericchiang** [comment]
Dex has options to use storage to persist keys. I recommend using that. For go-oidc we're just following the cache headers that are returned by dex.

It does look like the spec doesn't use cache control headers for verification though:

https://openid.net/specs/openid-connect-core-1_0.html#RotateSigKeys

> Rotation of signing keys can be accomplished with the following approach. The signer publishes its keys in a JWK Set at its jwks_uri location and includes the kid of the signing key in the JOSE Header of each message to indicate to the verifier which key is to be used to validate the signature. Keys can be rolled over by periodically adding new keys to the JWK Set at the jwks_uri location. The signer can begin using a new key at its discretion and signals the change to the verifier using the kid value. The verifier knows to go back to the jwks_uri location to re-retrieve the keys when it sees an unfamiliar kid value. The JWK Set document at the jwks_uri SHOULD retain recently decommissioned signing keys for a reasonable period of time to facilitate a smooth transition.

Maybe we could just refresh whenever we see an unfamiliar `kid` value? It'd be nice to remove the cache control parser as a dependency.

cc @mikedanese

**Comment by fezho** [comment]
I can avoid this error by using persistent volume for dex, thanks @ericchiang . Meanwhile, there's a workaround to fix this issue in argo-cd: https://github.com/argoproj/argo-cd/pull/1114

**Comment by ericchiang** [comment]
Thanks, closing this for now
