### ISSUE TITLE
Get data from token without pre-knowledge of the issuer nor validation

### ISSUE THREAD

**Issue by HankTheCrank** [coreos/go-oidc#252]
The approach as I have seen it is to get a token, verify it, then work with the returned IDToken to get the elements. This means that I have to wait for a round trip to an issuer that may not be the right one for this token. I'd rather do preliminary testing before wasting the time on the call. This would apply to the clientid as well. I could save a lot of wasted round trips if I could test locally first. I know there are a lot of other libraries out there that could do this (eg https://jwt.io/ will decode a token with no prior information and lists the libraries) but I think this is something that would add value to go-oidc and not have to introduce another library to the code.

**Comment by ericchiang** [comment]
This package already does claim validation before making a request to the provider https://github.com/coreos/go-oidc/blob/v2/verify.go#L214-L216

If you have custom checks, I think the way to go is to implement something similar :) Getting data before validation introduces a lot of opportunities for misuse and vulnerabilities, so I'd have to see what API you're proposing before figuring out if it's suitable for this package.

**Comment by ericchiang** [comment]
So I think the answer remains to parse the token yourself if you want to do additional validation before checking the signature.
