### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by saito-kosuke** [coreos/go-oidc#263]
When I have executed the below,
`provider, err := oidc.NewProvider(ctx, "https://"+h.Auth0Domain+"/")`
the error "failed to get provider: Get https://hogehoge/.well-known/openid-configuration: net/http: TLS handshake timeout" has occurred to me.

Could you deal with it like the issue below?
https://github.com/dexidp/dex/issues/797

**Comment by ericchiang** [comment]
Sorry, this is going to be an issue with your network connection, and not likely an issue with go-oidc itself. Going to close for now, but please comment if you have a reproducible issue or think you've found a bug in this package.
