### ISSUE TITLE
package jose and package oidc not found

### ISSUE THREAD

**Issue by qinmaye** [coreos/go-oidc#270]
``` go
import (
	"github.com/coreos/go-oidc/jose"
)
```

```go
import (
	"github.com/coreos/go-oidc/oidc"
)
```

doc.go:25:2: module github.com/coreos/go-oidc@latest found (v2.2.1+incompatible), but does not contain package github.com/coreos/go-oidc/jose
forwarding.go:25:2: module github.com/coreos/go-oidc@latest found (v2.2.1+incompatible), but does not contain package github.com/coreos/go-oidc/oidc

**Comment by ericchiang** [comment]
These are old packages on the v1 branch that aren't maintained anymore (or fixed for security issues). I strongly recommend switching to the v2 branch.

**Comment by qinmaye** [comment]
> These are old packages on the v1 branch that aren't maintained anymore (or fixed for security issues). I strongly recommend switching to the v2 branch.

Thank you very much!
