### ISSUE TITLE
New provider error for certificate

### ISSUE THREAD

**Issue by BredSt** [coreos/go-oidc#271]
I use the following code 

    provider, err := oidc.NewProvider(ctx, providerURI)
    if err != nil {
    	log.Println(err)
    }

While running it locally **with same providerURI** it **works**, I was able to get the provider.

I deployed it to K8S with the **exact same provider url** (as `env` variable ) and debug it using port-forwarding with delve,
However, in k8S I got error and dont get the `provider`,
The error is:

    2020/08/14 16:42:22 Get "https://ace.svar.com/.well-known/openid-configuration": x509: certificate signed by unknown authority

How can I configure it, or avoid this error? 

I put under the root of my project(sibling to the main.go) the following file (`server.crt`, `server.key`) 

    http.ListenAndServeTLS(":"+port, "server.crt", "server.key", nil)

However, still I got the same error, as the code of the provider is called before, How should I pass it to the provider code ? using the docker file build process? 

**This is my container**

    FROM golang:1.14.7 AS builder
    RUN go get github.com/go-delve/delve/cmd/dlv
    RUN mkdir /app
    
    ADD . /app
    WORKDIR /app
    RUN CGO_ENABLED=0 GOOS=linux go build -gcflags="all=-N -l" -o main ./...
    
    FROM debian:buster AS production
    COPY --from=builder /app .
    COPY --from=builder /go/bin/dlv /
    EXPOSE 8000 40000
    ENV PORT=8000
    CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./main"]

  [1]: https://github.com/coreos/go-oidc

How should I add to the lib the certificate ?

**Comment by ericchiang** [comment]
If you need to you can modify the transport used for the HTTP request with ClientContext https://godoc.org/github.com/coreos/go-oidc#ClientContext

But it's likely because you don't have any CA certificates in your container https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image

Either way, this likely isn't an issue with go-oidc itself.

**Comment by BredSt** [comment]
@ericchiang  - thanks,

I've added the certificate like the following:

```
FROM golang:1.14.7 AS builder
RUN go get github.com/go-delve/delve/cmd/dlv
ADD server.crt /usr/local/share/ca-certificates/server.crt
RUN chmod 644 /usr/local/share/ca-certificates/server.crt && update-ca-certificates
RUN mkdir /app

ADD . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -gcflags="all=-N -l" -o main ./...

FROM debian:buster AS production
COPY --from=builder /app .
COPY --from=builder /go/bin/dlv /
COPY --from=builder /usr/local/share/ca-certificates/ /usr/local/share/ca-certificates/
EXPOSE 8000 40000
ENV PORT=8000
CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./main"]
```

To verify, I've  `exec` into k8s container after deploy and I see the `server.crt` file under `/usr/local/share/ca-certificates/` .
And still I got the same issue.

Where I think its related to`go-oidc` , we are now in a middle transitions for some app from NodeJS to GO and in node we use the following for the **exact same issuer**
https://github.com/panva/node-openid-client

```
const { Issuer } = require('openid-client');
Issuer.discover( `${providerURI}/.well-known/openid-configuration`;)
  .then(function (Issuer) {
    console.log('Discovered issuer %s %O', Issuer.issuer, Issuer.metadata);
  }); 
```

The node docker file **doesn't contain** any certificate and it works. Any idea why? how to overcome this?
I've found also this https://github.com/kubernetes/apiserver/blob/211b614cb67c88718fbeb03589b2ad1a16040f22/plugin/pkg/authenticator/token/oidc/oidc.go#L275  not sure its related

**Comment by ericchiang** [comment]
I believe this is an issue with the interaction between your docker container and https://golang.org/pkg/crypto/tls/, so I don't plan on helping debug. You may want to consider https://golang.org/help/

If you do think you've found an issue with go-oidc specifically, not just the Go standard library, feel free to leave a comment replying to the workaround of using a custom HTTP Client in https://github.com/coreos/go-oidc/issues/271#issuecomment-674275849
