### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by owen-kuai** [coreos/go-oidc#273]
Hello,  I'm using this package for development, it's really good to use, but recently I've had some problems on docking some self-signed supported oidcserver. Because the certificates on the server side are self-signed, I want to skip the validation of the relevant tls when I use them, but I can't find the relevant skip settings. Then I got the following error.

2020/08/24 12:01:06 Get "https://172.16.188.1:30034/api/v1/.well-known/openid-configuration": x509: certificate signed by unknown authority

My code is as follows:
provider, err := oidc.NewProvider(ctx, "https://172.16.188.1:30034/api/v1/")
	if err != nil {
		log.Fatal(err)
	}

**Comment by ericchiang** [comment]
You want ClientContext, which lets you customize the HTTP client and use custom certificates https://godoc.org/github.com/coreos/go-oidc#ClientContext
