### ISSUE TITLE
Support for defining what claim a validation is made against to support providers like AWS Cognito for M2M calls.

### ISSUE THREAD

**Issue by lyndon160** [coreos/go-oidc#280]
# Context

I am trying to use the `go-oidc` library for validating machine to machine (m2m) tokens from AWS Cognito. In particular, I am doing this through the popular identity proxy `oauth2-proxy`, which uses the `go-oidc` library. Related issue here: https://github.com/oauth2-proxy/oauth2-proxy/issues/891

The setup is as follows:

Machine (Cognito Client (client_creds)) -> oauth2-proxy (Cognito Client).

In this setup, the proxy uses https://github.com/coreos/go-oidc/blob/v2/verify.go#L79 to validate the audience of the machine client, against the proxy client. However, when using client_creds flow, only an **access token** is returned, which with AWS Cognito does not return the 'aud' field. As far as I understand, this makes it not compatible with `go-oidc`, as it is hardcoded to match against the 'aud' field. The alternative to this is to set `SkipClientIDCheck`, however, this means that any client within the same provider instance can be used, in some deployments this does not provide the required security.

As an example, here's the payload of an AWS Cognito access token:

```
{
  "sub": "xxxxxxxxxxxxxxxxxx",
  "token_use": "access",
  "scope": "xxxxxx",
  "auth_time": 1604476544,
  "iss": "https://cognito-idp.eu-west-2.amazonaws.com/xxxxxxxx",
  "exp": 1604480144,
  "iat": 1604476544,
  "version": 2,
  "jti": "xxxxxx",
  "client_id": "xxxxxxx".     <------- replaces aud claim (feature of AWS Cognito)
}
```

This appears to be because AWS Cognito uses the `client_id` claim instead: https://stackoverflow.com/questions/53148711/why-doesnt-amazon-cognito-return-an-audience-field-in-its-access-tokens

# Suggested solution

Offer an override for client validation around the  'aud' field. To support AWS Cognito, this should be configurable to another claim name. In this case, the `client_id` claim.

**Comment by ericchiang** [comment]
If we provided an override to allow the client_id then other clients would need to be updated anyway. Can you just do:

```go
c := oidc.Config{SkipClientIDCheck: true}
v := p.Verifier(&c)
t, err  := v.Verify(ctx, idToken)
if err != nil {
    // ...
}
var claims struct {
    ClientID string `json:"client_id"`
}
if err := t.Claims(&claims); err != nil {
    // ...
}
if claims.ClientID != clientID {
    // ...
}
```

**Comment by lyndon160** [comment]
Thanks @ericchiang.
