### ISSUE TITLE
Possible issue with verifying token expiry timestamp

### ISSUE THREAD

**Issue by j-zimnowoda** [coreos/go-oidc#281]
Hi,

I am getting an error:
```
oidc: token is expired (Token Expiry: 2020-11-25 13:47:33 +0000 UTC)
```

The token always contains UCT timestamp.
When I look at the `go-oidc` code it seems that it compares token timestamp against local time
see: https://github.com/coreos/go-oidc/blob/50700f92176680a141cb7ccb894de3b09a30b709/verify.go#L278
time.Now - https://golang.org/src/time/time.go?s=33254:33269#L1056

Could you confirm the issue?
Regards

**Comment by ericchiang** [comment]
If time.Now doesn't work you can provide your own time method

https://pkg.go.dev/github.com/coreos/go-oidc/#Config
