### ISSUE TITLE
Allow verification errors to be differentiated

### ISSUE THREAD

**Issue by bojanz** [coreos/go-oidc#283]
Right now the package uses fmt.Errorf() for all errors. For example:
```
return nil, fmt.Errorf("oidc: token is expired (Token Expiry: %v)", t.Expiry)
```
This prevents callers from being able to identify individual errors. For example, a middleware wanting to return "Bad credentials." for most generic failures, but "Token expired." specifically for that one error. Right now I am forced to do a strings.Contains to identify a token expiration error.

My suggestion is to define sentinel errors (e.g ErrTokenExpired) for cases where the additional context is irrelevant*,  and to define custom error types (e.g. TokenExpiredError) where the context is relevant.

* I'd argue that including t.Expiry in this error isn't super helpful cause it's my token and I already know the expiration, but it's definitely subjective.

**Comment by ericchiang** [comment]
I'd be fine adding a custom error.

```go
type ExpiryError struct {
    Now    time.Time
    Expiry time.Time
}

func (e *ExpiryError) Error() string {
    return fmt.Sprintf("oidc: token is expired (Token Expiry: %v)", e.Expiry)
}
```

Feel free to send a PR. Though you may want to target the v3 branch since we're in the middle of getting that up and running.

**Comment by intinig** [comment]
I am working on a PR to the same tune right now, should raise it today.

**Comment by ericchiang** [comment]
When reviewing #292 I realized that expiry check is before the signature check, so this information is attacker controlled and probably shouldn't be exposed by our APIs. If you'd like to check the expiry, you can use "SkipExpiryCheck" then perform your own validation to get the error.

https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#Config

**Comment by ericchiang** [comment]
Since we already have SkipExpiryCheck, I'm going to close out this particular issue since that resolves @bojanz's initial feature request. @intinig if you need other introspection we can continue the conversation in #292
