### ISSUE TITLE
github.com/coreos/go-oidc/v3/oidc is empty

### ISSUE THREAD

**Issue by analizaBe** [coreos/go-oidc#287]
Hello! I'm trying to download 
go get github.com/coreos/go-oidc/v3
but take this response
package github.com/coreos/go-oidc/v3: cannot find package "github.com/coreos/go-oidc/v3" in any of:
        /usr/local/go/src/github.com/coreos/go-oidc/v3 (from $GOROOT)
        /Users/lalala/go/src/github.com/coreos/go-oidc/v3 (from $GOPATH)

**Comment by ericchiang** [comment]
Hey @analizaBe,

You probably want to try this using Go modules https://golang.org/ref/mod If you're working in a directory with a go.mod file the import should work.

```
$ go mod init github.com/ericchiang/test
go: creating new go.mod: module github.com/ericchiang/test
$ cat go.mod 
module github.com/ericchiang/test

go 1.15
$ go get github.com/coreos/go-oidc/v3
go: downloading github.com/coreos/go-oidc/v3 v3.0.0
go: downloading github.com/coreos/go-oidc v2.2.1+incompatible
go: github.com/coreos/go-oidc/v3 upgrade => v3.0.0
$ cat go.mod 
module github.com/ericchiang/test

go 1.15

require github.com/coreos/go-oidc/v3 v3.0.0 // indirect
```

If you have to use GOPATH instead, then the import path is github.com/coreos/go-oidc/oidc. But we recommend switching to go mod.
