### ISSUE TITLE
URL query params are null after redirection?

### ISSUE THREAD

**Issue by smartaquarius10** [coreos/go-oidc#297]
Hello,

I'm trying to integrate this with on-prem system. After redirection, the url changes to the one specified in handler and there is nothing left in the query params.

I am following this [example](https://github.com/coreos/go-oidc/blob/v3/example/userinfo/app.go) but it is regularly throwing an error:- `state did not match`

If I replace `r.URL.Query().Get("state")` to `r.FormValue("state")` then it works. Is this approach correct. Can we use `r.FormValue` in production.

Please help. 

Thank you

**Comment by ericchiang** [comment]
You may want to use your browsers devtools to see what requests are being made. Either way this doesn't seem like an issue with this library so closing.

**Comment by smartaquarius10** [comment]
@ericchiang, sure thanx
