### ISSUE TITLE
Flow with a SPA

### ISSUE THREAD

**Issue by cedricve** [coreos/go-oidc#300]
Hello, this is amazing work, i love it!

I was just wondering how this fits into a SPA (Single Page Application). I understand the OIDC flow, but typically the entrypoint of an app is at a SPA page. When pressing a login button, one can take them to the OIDC endpoint, and from there request the scope. When successfull the user is send back to the redirect_url, but then I'm wondering how you get the JWT token back into the client..

**Comment by ericchiang** [comment]
You may want to look into the OpenID Connect implicit flow, which this package intentionally doesn't support https://openid.net/specs/openid-connect-core-1_0.html#ImplicitFlowAuth

Closing since this is a question not a big, and the maintainers don't have a lot of bandwidth.
