### ISSUE TITLE
How to use refresh token to update id token?

### ISSUE THREAD

**Issue by smartaquarius10** [coreos/go-oidc#301]
Hello,

I'm using the authentication flow of OIDC for which I have followed this [example](https://github.com/coreos/go-oidc/tree/v3/example/idtoken).

We are getting the refresh token in the output but unable to understand the procedure to use it within this OIDC flow. 

I've also gone through this [issue ](https://github.com/coreos/go-oidc/issues/199)but still no luck. Can anyone please suggest me how to use refresh token in this oidc flow. 

Thank you

**Comment by smartaquarius10** [comment]
@ericchiang ,Hello Eric, 
Hope you're doing well. Could please guide me a little. I'm pretty new with OIDC stuff and using refresh token in auth flow. 

Thank you

**Comment by ericchiang** [comment]
Thanks for the bug. Unfortunately we don't have bandwidth for these kind of support questions. I suggest looking into #199 more
