### ISSUE TITLE
Is ES256 verification is not supported?

### ISSUE THREAD

**Issue by smartaquarius10** [coreos/go-oidc#302]
Hello,

I have used custom verifier with JWKS via HTTPS

verifier := oidc.NewVerifier("<issuer url>", oidc.NewRemoteKeySet(ctx, "<url>/af/JWKS"), oidcConfig). 

> It returns an array of key sets(kid, EC, RSA etc.).

The moment I hit url it returns error at this point `verifier.Verify(ctx, rawIDToken)` 

`Failed to verify ID Token: oidc: id token signed with unsupported algorithm, expected ["RS256"] got "ES256"`

Is there any mistake in the way I used. Any suggestion please. Thank you.

**Comment by ericchiang** [comment]
Verifier should default to whatever algorithms your provider advertises

https://github.com/coreos/go-oidc/blob/15b94d97d90c9455981dbdd90a021d34254cfdaf/oidc/verify.go#L105-L118

If you build this from NewVerifier you need to supply SupportedSigningAlgs directly.

https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#Config

does that work?

**Comment by smartaquarius10** [comment]
@ericchiang , Hey eric, thanks for sharing.

I have gone through the code you have shared and found that provider.remotekeyset has already pulled the exact jwks url for well-known url. Then jose.ParseSigned filtered the required signature. 

It is already handled. I can go with the existing one. Now the only thing left is to understand the procedure of using refresh token. 

One thing more, if you have any example or url explaining the payload verification using CA cert public key then please let me know. Currently, I'm not receiving any header like x5c etc.  

You can close this issue. Thank you for the help. Take care.

**Comment by ericchiang** [comment]
To verify with x509 certificates, you'd want to implement KeySet and use NewVerifier

https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#KeySet
https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#NewVerifier

Something like this?

```go
import (
    // ...
    jose "gopkg.in/square/go-jose.v2"
    // ...
)

type x509KeySet struct {
    certs []*x509.Certificate
}

func (ks *x509KeySet) VerifySignature(ctx context.Context, jwt string) (payload []byte, err error) {
    jws, err := jose.ParseSigned(jwt)
    if err != nil {
        return nil, err
    }

    var lastErr error
    for _, cert := range ks.certs {
        payload, err := jws.Verify(cert.PublicKey)
        if err == nil {
            return payload, nil
        }
        lastErr = err
    }
    return nil, lastErr
}
```

If this comes up a lot, maybe we could add a helper to turn a set of crypto.PublicKeys into a KeySet

```
func NewStaticKeySet(pubs ...crypto.PublicKey) KeySet {
    // ...
}
```

Anyway, closing for now.

**Comment by smartaquarius10** [comment]
@ericchiang , You’re awesome. Thank you very much. Take care. Happy weekend🙂👍
