### ISSUE TITLE
Is it possible to set relative path in redirect url?

### ISSUE THREAD

**Issue by smartaquarius10** [coreos/go-oidc#304]
Hello,

I need to host the application in Azure as app service. Is it possible to set relative path in this [section](https://github.com/coreos/go-oidc/blob/15b94d97d90c9455981dbdd90a021d34254cfdaf/example/idtoken/app.go#L61)
`RedirectURL:  "http://127.0.0.1:5556/auth/google/callback",`

Something like this 

`RedirectURL:  "/auth/google/callback",`

**Comment by smartaquarius10** [comment]
@ericchiang , Hey eric.. Hope you're doing well. 

Once free, could you please help on this. Thank you. Take care..

Regards
Tanul

**Comment by ericchiang** [comment]
Sorry I don't have a lot of free bandwidth to answer questions about this project. If there's a bug or feature request please feel free to open an issue, but closing this out.
