### ISSUE TITLE
Add scopes_supported to providerJSON

### ISSUE THREAD

**Issue by abatilo** [coreos/go-oidc#313]
https://openid.net/specs/openid-connect-discovery-1_0.html

`scopes_supported` could be handed directly to an `oauth2.Config` structure the same way we can pass in `provider.Endpoint()`. It would be lovely if we could also just pass in `provider.ScopesSupported`.

**Comment by ericchiang** [comment]
Sgtm. Feel free send a pr :)

**Comment by ericchiang** [comment]
Also, just so you know, you can already get this data with Provider.Claims(). In hindsight, that might be a better option:

```
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/coreos/go-oidc/v3/oidc"
)

func main() {
	p, err := oidc.NewProvider(context.Background(), "https://accounts.google.com")
	if err != nil {
		log.Fatalf("new provider: %v", err)
	}
	var claims struct {
		SupportedScopes []string `json:"scopes_supported"`
	}
	if err := p.Claims(&claims); err != nil {
		log.Fatalf("decoding claims: %v", err)
	}
	for _, scope := range claims.SupportedScopes {
		fmt.Println(scope)
	}
}
```

**Comment by abatilo** [comment]
Oh, that's even better. Thanks!
