### ISSUE TITLE
Support self-signed certificate

### ISSUE THREAD

**Issue by sylock** [coreos/go-oidc#321]
Hi,

I'm a user of Argo Workflow which uses go-oidc. When trying to setup authentication it fails since my certificate is self-signed. I do no see a way to configure a "skip certificate validation" or something similar.

Here is the related ticket to the downstream project Argo Workflow : https://github.com/argoproj/argo-workflows/issues/6793

Is it something possible to implement?

**Comment by ericchiang** [comment]
You can use ClientContext to configure the HTTP client used to connect to the provider.

https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#ClientContext

Client transports take TLS config options

https://pkg.go.dev/net/http#Transport

So already supported :)
