### ISSUE TITLE
code_challenge is missing

### ISSUE THREAD

**Issue by mTLamouchi** [coreos/go-oidc#322]
Hi, I am using go-iodc with identity server 4, I have followed exactly the userinfo example but the identity server return a code challenge is missing error

**Comment by ericchiang** [comment]
This package only deals with OpenID Connect details. This sounds like a generic OAuth2 feature.

https://datatracker.ietf.org/doc/html/rfc7636
https://www.oauth.com/oauth2-servers/pkce/authorization-request/

You may want to open a request with Identity Server 4 for help. From what I can see this isn't part of the OpenID Connect specification.

https://openid.net/specs/openid-connect-core-1_0.html

**Comment by arukiidou** [comment]
- it was implemented by upstream.
  - https://pkg.go.dev/golang.org/x/oauth2@v0.13.0#S256ChallengeOption
