### ISSUE TITLE
Help wanted for SPA (react) + code flow 

### ISSUE THREAD

**Issue by fl0wx** [coreos/go-oidc#331]
How do i implement the REST Server Part of the Code Flow Authentication in combination with a SPA ? 
Like statet here: https://security.stackexchange.com/questions/129928/oidc-flow-for-spa-and-restful-api

```
**Authorization Code Flow**

1. User navigates to SPA, which redirects user to IdP to sign in.
2. User signs in (and authorizes the application, if needed).
3. IdP returns user to SPA with Authorization Code.
4. JavaScript code in SPA sends the Authorization Code to a login endpoint on the REST API Server.
5. The REST API Server sends a request to the IdP Server containing the Authorization Code (and usually also a Client ID and Client Secret which identify the REST API Server to the IdP server).
6. The IdP validates the Authorization Code and sends the Access Token and ID Token to the REST API Server.
7. The REST API Server stores the Access Token and ID Token in its memory, and sends its own Session Token back to the SPA.
8. For every request the SPA makes to the REST API Server, it includes the Session Token which the REST API Server gave it. If the REST API Server needs to request resources from another server, it uses the stored Access Token to make that request.
```

I also would like to add that I have to do additional queries against ldap to get the roles of the current user. Our oidc does not include any authorization data and is only used for login.

Any help with that? Or hints what to do? 

Thanks and regards, fl0w

**Comment by ericchiang** [comment]
Sorry for the delay here. Unfortunately this doesn't really sound like a question for this package. go-oidc is only about validating ID tokens, not broader OAuth2, which is handled by golang.org/x/oauth2

If there's something that can be added to this API, happy to discuss that. But closing out for now.
