### ISSUE TITLE
Make ClientID in Config an array

### ISSUE THREAD

**Issue by splaunov** [coreos/go-oidc#334]
Currently only single value can be set in config to validate IDToken audience:

https://github.com/coreos/go-oidc/blob/2d47dd95152744f41009de5797efe6cc07832a41/oidc/verify.go#L74-L79

But Apple sets different values to `aud` field in id token depending on application type:
- they use Service Id for web applications

- and Bundle Id for iOS/macOS

And there is no way to set both Service Id and Bundle Id to the same value:

https://stackoverflow.com/questions/61848382/using-the-same-services-id-identifier-as-app-id

My proposal is to allow for an array in go-oidc config to set all allowed identifiers for audience validation.

I'm interested to contribute this change if the idea looks good to go-oidc supporters.

**Comment by ericchiang** [comment]
I'd recommend using the SkipClientIDCheck and doing this check manually. Custom logic like this is what it's there for. Does that work? :)

Presumably, you also want to have different behavior based on if the token was generated through the web application or native app anyway?

**Comment by mitar** [comment]
I would also prefer if this could be an array, given that it can be based on the spec. It is much easier to have it an array and validate it based on that, and then after validation you can have custom logic to do different things based on which client ID is there.

**Comment by ericchiang** [comment]
There's nuance here. For example, do you expect all client IDs to match the array, or is some overlap okay. Different scenarios might require different logic.

In these cases, the answer is SkipClientIDCheck. Since we already have a solution I'm against adding another one.

**Comment by mitar** [comment]
Thanks for taking the time to explain. I agree with you now.

**Comment by splaunov** [comment]
>I'd recommend using the SkipClientIDCheck and doing this check manually.

We have resolved our case in this way. As for me, this issue can be closed.
Thank you!
