### ISSUE TITLE
IDTokenVerifier from Provider

### ISSUE THREAD

**Issue by mitar** [coreos/go-oidc#335]
`Provider.Verifier`'s documentation currently states:

> The returned IDTokenVerifier is tied to the Provider's context and its behavior is undefined once the Provider's context is canceled. 

Looking at the code I do not see this to be true. There is no context being passed from `Provider` to `IDTokenVerifier`. There is no context even saved into `Provider`. The only context is inside `RemoteKeySet` but even that one explicitly creates a new/cloned context using `context.Background()`.

I think this line should be removed from documentation.

**Comment by ericchiang** [comment]
I think those are a hold over from the old logic :)

Feel free to send a PR

**Comment by mitar** [comment]
Done: https://github.com/coreos/go-oidc/pull/336
