### ISSUE TITLE
issuer did not match the issuer returned by provider, expected "https://xxxxx.com" got "https://xxxxx.com/"

### ISSUE THREAD

**Issue by shuaiganzi** [coreos/go-oidc#338]
issuer with '/', return error

**Comment by ericchiang** [comment]
The openid connect spec is pretty strict about issuer strings using exact matches. Please provide `https://xxxxx.com/` when constructing your provider.

* https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation
* https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata
* https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
