### ISSUE TITLE
404 error while trying to get user info from keycloak

### ISSUE THREAD

**Issue by mhkarimi1383** [coreos/go-oidc#343]
I have just used provided examples and changed things to make it work with my own keycloak
but after successful login it will redirect me to `/auth/openid/callback` and I get `Page not found` error
I can provide my code if needed

thanks

**Comment by ericchiang** [comment]
Hey @mhkarimi1383,

Unfortunately I don't provide support on this issue tracker (I maintain this package in my spare time). And what you're describing doesn't sound like a bug in this package. If Keycloak has a support form or somewhere to ask questions, that might be a better place for this kind of a question.
