### ISSUE TITLE
Verify calls jose.ParseSigned twice

### ISSUE THREAD

**Issue by horpto** [coreos/go-oidc#346]
`jwt string` is quite common type to not depend on implementation. But maybe is better to create intermediate representation of parsed?

![изображение](https://user-images.githubusercontent.com/7109350/187547270-6733b968-af72-475c-9461-6cb64152688f.png)

**Comment by ericchiang** [comment]
Do you have a reproducer or some context of how go-oidc is being called? I only see jose.ParseSigned called once on the code

**Comment by horpto** [comment]
1) https://github.com/coreos/go-oidc/blob/v3/oidc/verify.go#L199 - first call
2)
https://github.com/coreos/go-oidc/blob/v3/oidc/verify.go#L311 - `gotPayload, err := v.keySet.VerifySignature(ctx, rawIDToken)`
https://github.com/coreos/go-oidc/blob/v3/oidc/jwks.go#L122 - `jws, err := jose.ParseSigned(jwt)`
and second call in RemoteKeySet

**Comment by ericchiang** [comment]
Thanks! Should be fixed by https://github.com/coreos/go-oidc/pull/347

**Comment by horpto** [comment]
Thanks! Really fast! I guess other KeySet implementations will be affected too
