### ISSUE TITLE
How to force re-authentication?

### ISSUE THREAD

**Issue by patrickjane** [coreos/go-oidc#353]
As described here:
https://keycloak.discourse.group/t/force-re-authentication-with-prompt-login-or-max-age-0-does-not-work/9315

It should be possible to force the Identity Provider to present a new login form, even when the user is already logged in. This is supposed to work by supplying the `prompt=login` parameter or setting `max_age` to 0 in the request to the IdP.

Is this possible with this library? How can I do this?

**Comment by ericchiang** [comment]
For prompt=login, you want [oauth2.SetAuthURLParam](https://pkg.go.dev/golang.org/x/oauth2#SetAuthURLParam)

Unfortunately, I think this is a better question for your provider (e.g. Keycloak).
