### ISSUE TITLE
provider well-known configuration URL is not created per spec

### ISSUE THREAD

**Issue by gotwarlost** [coreos/go-oidc#359]
I was going through the code just to make sure that my somewhat exotic use-case would work correctly and I happened to notice an unrelated issue.

https://www.rfc-editor.org/rfc/rfc8414.html#section-3

Authorization servers supporting metadata MUST make a JSON document containing metadata as specified in [Section 2](https://www.rfc-editor.org/rfc/rfc8414.html#section-2) available at a path formed by inserting a well-known URI string into the authorization server's issuer identifier **between the host component and the path component, if any** . (emphasis mine)

https://github.com/coreos/go-oidc/blob/fb9e00951dc7a7d035e7664a5df116c3563afbd7/oidc/oidc.go#L184

simply appends to the URL after trimming the trailing `/` which means for an auth server having an issuer URL of `https://example.com/foo` the well-known path is constructed as `https://example.com/foo/.well-known/openid-configuration` whereas it should have been `https://example.com/.well-known/openid-configuration/foo`

**Comment by gotwarlost** [comment]
Oops. It looks like Okta, at least, implements it in a way that is compatible with the current code and not the spec. Maybe I haven't quite understood the spec in that case :(

**Comment by ericchiang** [comment]
Hey! I'm not super familiar with RFC 8414. The specifications that govern OpenID Connect can be found at: https://openid.net/developers/specs/

Logic for constructing the URL is here: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig

> OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string /.well-known/openid-configuration to the Issuer. The syntax and semantics of .well-known are defined in [RFC 5785](https://openid.net/specs/openid-connect-discovery-1_0.html#RFC5785) [RFC5785] and apply to the Issuer value when it contains no path component. openid-configuration MUST point to a JSON document compliant with this specification and MUST be returned using the application/json content type.

Section 4.1 continues with an example to illustrate this:

> If the Issuer value contains a path component, any terminating / MUST be removed before appending /.well-known/openid-configuration. The RP would make the following request to the Issuer https://example.com/issuer1 to obtain its Configuration information, since the Issuer contains a path component:
> ```
> GET /issuer1/.well-known/openid-configuration HTTP/1.1
> Host: example.com
> ```

Going to close out since (as you mentioned) it looks like other providers are following the OpenID Connect spec :)

Please reopen if I've misread anything!

**Comment by gotwarlost** [comment]
yes, sorry for the noise. Just read it now and came here to close the issue as invalid.
