### ISSUE TITLE
Use context in new requests

### ISSUE THREAD

**Issue by argenta-quanto** [coreos/go-oidc#362]
In some methods the code below do not use the context passed thought the method:
ex:

```
func (p *Provider) UserInfo(ctx context.Context, tokenSource oauth2.TokenSource) (*UserInfo, error) {
	...
	if p.userInfoURL == "" {
		return nil, errors.New("oidc: user info endpoint is not supported by this provider")
	}

	req, err := http.NewRequest("GET", p.userInfoURL, nil)
	...

```

There is something that create some kind of risk in using :
`	req, err := http.NewRequestWithContext(ctx, "GET", p.userInfoURL, nil)`

?

Thanks.

**Comment by argenta-quanto** [comment]
Made a PR:

https://github.com/coreos/go-oidc/pull/363

**Comment by ericchiang** [comment]
Can you take a look at #364?

**Comment by argenta-quanto** [comment]
> Can you take a look at #364?

Yes, this is what I need.
Thanks.
