### ISSUE TITLE
Non-expiring JWT is rejected as expired

### ISSUE THREAD

**Issue by ghost** [coreos/go-oidc#371]
Our OIDC IdP allows for issuing API tokens that do not expire. We are validating these API tokens through oauth2-proxy, which uses go-oidc to perform the validation.

These tokens do not have the `exp` claim set. When attempting to authenticate with this token, oauth2-proxy echoes this error from go-oidc:

```
oidc: token is expired (Token Expiry: 0001-01-01 00:00:00 +0000 UTC)
```

This error seems to be returned here: https://github.com/coreos/go-oidc/blob/921a42b4b63d5b618d17d7e7a36a4acb59e643c6/oidc/verify.go#L293

**Comment by ericchiang** [comment]
Hey!

Expiry is a required field https://openid.net/specs/openid-connect-core-1_0.html#IDToken

Based on my reading of the spec, an ID Token without an exp is invalid, so I don't know if we want to support this. Can you add an arbitrarily long expiry instead?

**Comment by ghost** [comment]
I don't have control over the tokens myself, but I'll forward the matter to the IdP and see if they can accommodate that.

**Comment by ericchiang** [comment]
Sounds good! going to close this out per the spec requirement. Please comment (or have someone form your IdP comment) if this still needs to be addressed by the library
