### ISSUE TITLE
Backport PR 249 to 2.x stream?

### ISSUE THREAD

**Issue by tstephen-relx** [coreos/go-oidc#383]
I realise that it doesn't look like you are maintaining v2 now that v3 is out but because of third party dependencies I am stuck on the 2.x stream. 

I wonder if you would be open to a contribution that backported PR 249, which increases the tolerance for mis-typed email_verified values?

Thanks for your consideration, and understanding if you prefer not.
Tim

**Comment by ericchiang** [comment]
https://github.com/coreos/go-oidc/pull/249 was never merged

See my justification here: https://github.com/coreos/go-oidc/pull/249#issuecomment-634320065

I don't think we'd take this change, since it's against the spec. It's effectively a bug in the upstream provider

**Comment by tstephen-relx** [comment]
Many thanks, closing this.
