### ISSUE TITLE
Test with go 1.20/ go 1.21

### ISSUE THREAD

**Issue by arukiidou** [coreos/go-oidc#388]
### goals

Go 1.21 is released. add test with go 1.20 / go 1.21

### tasks

- [x] add matrix test
- [x] test with go 1.20/ go 1.21

### non-goals

- bump [actions/setup-go](https://github.com/actions/setup-go) and [actions/checkout](https://github.com/actions/checkout)
- drop go 1.19

### sample

https://github.com/actions/setup-go#matrix-testing

**Comment by ericchiang** [comment]
Fixed with #419
