### ISSUE TITLE
Bump actions/checkout@v3, actions/setup-go@v4

### ISSUE THREAD

**Issue by arukiidou** [coreos/go-oidc#391]
### Summary

Bump actions/checkout@v3, actions/setup-go@v4

### Why?

- [Linux (1.21)](https://github.com/arukiidou/go-oidc/actions/runs/5879726585/job/15944440880) Cause warnings: `the following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-go@v2, actions/checkout@v2.`
  - see: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

![image](https://github.com/coreos/go-oidc/assets/10738333/5dc86788-de04-40cf-8ea0-fd0d92ae7286)

**Comment by ericchiang** [comment]
Fixed in #419
