### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Gartito** [coreos/go-oidc#403]
Hi guys, I'm trying to use steam as an OpenID Provider. Until weeks ago I was successfully handling the authentication and receiving the steamID, but now the redirect url is returning this:
![image](https://github.com/coreos/go-oidc/assets/91842180/10d119f5-a0aa-47ee-9b83-b7c158fe0ac0)

Someone have an idea what's happening?

**Comment by ericchiang** [comment]
Sorry, I don't think this is related to this package. You'll have to take it up with whoever runs the server for that URL
