### ISSUE TITLE
Add custom issuer validation for discovery based Providers creation

### ISSUE THREAD

**Issue by yuri-potatoq** [coreos/go-oidc#431]
I really want to thank you for the helpful project. It is very useful for OIDC auth validations.

Unfortunately i have the same problem solved by [InsecureIssuerURLContext ](https://github.com/coreos/go-oidc/blob/v3/oidc/oidc.go#L68-L83), with Keycloak OIDC discovery hostnames.

When i used the custom context to figure out it, i was wondering if a new feature to customize the issuers validation on Provider creation should fit in the project design. The goal is to accept trusted internal hosts at the issuer validation.

I make this [PR](https://github.com/yuri-potatoq/go-oidc/pull/1/files) to make a simple solution. I've designed in that way to avoid break changes.
Could u tell me if that could fit as a offical PR?

**Comment by ericchiang** [comment]
Since you can already do comparisons after providing the insecure issuer option, I don't think we need another hook.

**Comment by yuri-potatoq** [comment]
Hey, thank you to reply. That sounds suitable enough. But my point is about to centralize OIDC configuration stuff into the provider library, can be helpful to when the users has serveral microservices which share the same validation behavior and then package such logic to be reusable.

It's was just to clarify my intentions, if still not the library goal, i'm ok.
