### ISSUE TITLE
"best practice" to store the JWT?  In-memory / local seems to be the answer but how?

### ISSUE THREAD

**Issue by lknite** [coreos/go-oidc#443]
After logging in I should be able to browse to other urls.

I've used oidc for years to obtain a jwt and send the access token via restapis as a header.  But now I need to handle a login in the usual way via the browser, but then I need additional web pages.

Do I set a cookie after obtaining the token via the callback url?  Google says "definitely not, that's not safe".

When I google where to store the JWT is says in-memory or local but when I search for go and those I'm not finding much.

Seems like this would be common?  I would have thought there'd be a second example doing this on the main README.md, or a url to how to handle the token once obtained to set a cookie, or more appropriate "best practices" solution.

**Comment by ericchiang** [comment]
A basic flow for any web app is to authenticate the user, generate a session ID, store that ID in a database with information about the session, then return that ID in a cookie. On subsequent requests, the browser presents the cookie, and you query the database to figure out the properties of the session (like the associated user).

See https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html

**Comment by lknite** [comment]
Thank you

**Comment by lknite** [comment]
Reference:
https://gowebexamples.com/sessions/
