### ISSUE TITLE
Replace jose package with go-jose

### ISSUE THREAD

**Issue by bsr203** [coreos/go-oidc#50]
Hi,

This is not an issue, but just to inform a library I found, which may be interest to you

https://github.com/square/go-jose

Looks well maintained and comprehensive.

Cheers,
bsr

**Comment by gtank** [comment]
It's more feature-complete and might have had more eyes on it. Worth investigating, since it would let us move away from PKCS1v15 RSA.

**Comment by ericchiang** [comment]
Spoke with @gtank about this offline.

Our current jose implementation has a lot of missing features (support for ecdsa Keys), as well as documentation issues (for instance we've had internal issues with developers not correctly verifying JWTs).

While migrating isn't a top priority, in the long term I think it's best for us to deprecate the jose package and move to square/go-jose.

**Comment by ericchiang** [comment]
done https://github.com/coreos/go-oidc/pull/110
