### ISSUE TITLE
go-oidc/http package pulls in test-only net/http/httptest

### ISSUE THREAD

**Issue by timstclair** [coreos/go-oidc#57]
The go `net/http/httptest` package should only be used in test builds. In particular, that package adds the `httptest.serve` flag which leaks into binaries depending on go-oidc (e.g. https://github.com/kubernetes/kubernetes/issues/21114)

From what I can tell, the [`HandlerClient`](https://github.com/coreos/go-oidc/blob/46fc3c20dcad27d27596c8832b354621bdd8b88f/http/client.go#L13) that uses `httptest` is only used in testing, so I suggest moving it to a test-only package (such as `go-oidc/http/testing` or `go-oidc/http/httptest`)

**Comment by ericchiang** [comment]
Thanks, will do. We'll provide a PR to k8s as soon as we move it.
