### ISSUE TITLE
cli example question

### ISSUE THREAD

**Issue by rajeevb2** [coreos/go-oidc#60]
I was able to build the cli/main.go example. I setup openid provider with Google and specified the id and secret. I was unable to verify with the provider. 

clientID := fs.String("client-id", "<clid>", "")
clientSecret := fs.String("client-secret", "<clsec>", "")
discovery := fs.String("discovery", "https://accounts.google.com", "")

I added the id to the first string and secret for the first string. **What is the second string argument for clientID and clientSecret.**

I did get a response back from the provider but it appears that **I didn't specify my email/password**. Where do you specify that?

See response from provider
fetching provider config from https://accounts.google.com...fetched provider config from https://accounts.google.com: oidc.ProviderConfig{Issuer:(*url.URL)(0xstuff), AuthEndpoint:(*url.URL)(0xstuff), TokenEndpoint:(*url.URL)(0xstuff), UserInfoEndpoint:(*url.URL)(0xstuff), KeysEndpoint:(*url.URL)(0xstuff), RegistrationEndpoint:(*url.URL)(nil), ScopesSupported:[]string{"openid", "email", "profile"}, ResponseTypesSupported:[]string{"code", "token", "id_token", "code token", "code id_token", "token id_token", "code token id_token", "none"}, ResponseModesSupported:[]string(nil), GrantTypesSupported:[]string(nil), ACRValuesSupported:[]string(nil), SubjectTypesSupported:[]string{"public"}, IDTokenSigningAlgValues:[]string{"RS256"}, IDTokenEncryptionAlgValues:[]string(nil), IDTokenEncryptionEncValues:[]string(nil), UserInfoSigningAlgValues:[]string(nil), UserInfoEncryptionAlgValues:[]string(nil), UserInfoEncryptionEncValues:[]string(nil), ReqObjSigningAlgValues:[]string(nil), ReqObjEncryptionAlgValues:[]string(nil), ReqObjEncryptionEncValues:[]string(nil), TokenEndpointAuthMethodsSupported:[]string{"client_secret_post", "client_secret_basic"}, TokenEndpointAuthSigningAlgValuesSupported:[]string(nil), DisplayValuesSupported:[]string(nil), ClaimTypesSupported:[]string(nil), ClaimsSupported:[]string{"aud", "email", "email_verified", "exp", "family_name", "given_name", "iat", "iss", "locale", "name", "picture", "sub"}, ServiceDocs:(*url.URL)(nil), ClaimsLocalsSupported:[]string(nil), UILocalsSupported:[]string(nil), ClaimsParameterSupported:false, RequestParameterSupported:false, RequestURIParamaterSupported:false, RequireRequestURIRegistration:false, Policy:(*url.URL)(nil), TermsOfService:(*url.URL)(nil), ExpiresAt:time.Time{sec:63592531749, nsec:562120021, loc:(*time.Location)(0xstuff)}}

unable to verify auth code with issuer: client_credentials grant type is not supported

**Comment by ceroloy** [comment]
You specify them in

    cc = oidc.ClientCredentials{
		ID:     *clientID,
		Secret: *clientSecret,
	}

and then use cc in

    ccfg := oidc.ClientConfig{
		ProviderConfig: cfg,
		Credentials:    cc,
	}

and you pass ccfg to 

    client, err := oidc.NewClient(ccfg)

**Comment by rajeevb2** [comment]
If I did what you asked, it would look like this:
clientID := fs.String("client-id", "user-name", "")
clientSecret := fs.String("client-secret", "password", "")

Where do I specify the openid connect client-ID that Google gave me when I registered into their program? I was expecting that Google will use that and user-name/password and return back my Google profile in a JWT that I unpack with the client-secret that Google gave me.

**Comment by rajeevb2** [comment]
After a few days of investigation, I found out that Google does not support grant_type password (or grant_type client_credentials). 

The examples/app/main.go worked. I was able to authenticate with Google. I have a new question on that, for which I will open a new issue.

This issue can be closed.
