### ISSUE TITLE
Handle trailing slash in Auth0 openid-configuration issuer

### ISSUE THREAD

**Issue by alberts** [coreos/go-oidc#66]
A bit of a snafu with FetchProviderConfig...

https://fullung.auth0.com/.well-known/openid-configuration has issuer:https://fullung.auth0.com/ but https://fullung.auth0.com//.well-known/openid-configuration (double slash intentional) is a 404.

This is a problem because provider.go simply does:

req, err := http.NewRequest("GET", r.issuerURL+discoveryConfigPath, nil)

and later:

if !urlEqual(cfg.Issuer.String(), r.issuerURL)

Probably want to change provider.go to do:

if !urlEqual(cfg.Issuer.String(), r.issuerURL) && !urlEqual(cfg.Issuer.String(), r.issuerURL+"/") {

Not sure that getting Auth0 to fix their endpoint is going to happen and there might be other OpenID providers out there that made the same mistake.

Thoughts appreciated.

**Comment by ericchiang** [comment]
> If the Issuer value contains a path component, any terminating / MUST be removed before appending /.well-known/openid-configuration.

https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest

Looks like this is legal (though odd).

Do you want to open a PR?

**Comment by alberts** [comment]
Will send a PR.
