### ISSUE TITLE
ClientCredentials.Secret should be a []byte

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/go-oidc#72]
That way, we'd get automatic decoding/encoding of base64 when serialize to and from JSON.

**Comment by ericchiang** [comment]
From what I can see, client_secrets cannot be arbitrary bytes, the must be within a character range https://tools.ietf.org/html/rfc6749#appendix-A.2

Is this attempting to solving an issue in dex? Maybe we should use an intermediate struct there.

**Comment by bobbyrullo** [comment]
you're right - closign this out.
