### ISSUE TITLE
Any plan adding OIDC server example?

### ISSUE THREAD

**Issue by GordonJiang** [coreos/go-oidc#73]
There is client and application example, any plan to add simple server example showing us how to host a OIDC server/identity provider by this library?

**Comment by GordonJiang** [comment]
I'm very interested to use this OIDC library as our product's authentication module. Need some doc or sample about how to use it to provide identity verification. 
BTW, what's the best way to add following questions about using this library, rather than opening issue here?

**Comment by ericchiang** [comment]
This package holds utilities for OpenID Connect providers, not necessarily a framework like [osin](https://github.com/RangelReale/osin), so a server example would be fairly involved. There aren't plans ATM to add such an example.

> BTW, what's the best way to add following questions about using this library, rather than opening issue here?

Feel free to reach out on the #coreos-dev IRC channel on freenode.

**Comment by GordonJiang** [comment]
HI, Eric, Thanks for your quick response. In fact i was trying to pick 
one between osin and go-oidc to implement our authentication module. To 
us, we need to achieve 3 goals:
1) manage user info registered on our web, those account can be 
authenticated (p0)
2) be able to let users using their google, microsoft, etc accounts to 
login (p1)
3) in the future, we might want to support other 3rd party web/app to 
use our oauth2, openID account (p2)


osin looks a promise oauth2 framework with comprehensive examples, but 
it doesn't have OpenID implemented. go-oidc starts late but it supports 
OpenID, and it's under coreos so I assume it will be better supported 
and maintain.

Any opinion or recommendation here? Appreciated!

Thanks
Gordon

**Comment by ericchiang** [comment]
osin is terrific, but it's unlikely to add OpenID Connect support naively since it would require:
* Expanding the storage interface for public and private keys.
* Allowing registration of OpenID Connect specific error types.
* Provide facilities for putting the ID Token in the [response output](https://godoc.org/github.com/RangelReale/osin#Response).

It may be reasonable to add your own OpenID Connect support to osin.

go-oidc provides utilities, not a framework. So again, it's hard to say how far it will get you.

Have you looked at [dex](https://github.com/coreos/dex)? Are there reasons you'd choose not to go with that?

**Comment by GordonJiang** [comment]
Eric, got u. I looked at dex as the start. But quickly faced a few issues:

1) dex is completely a blackbox running as service, executable, but not 
a library or framework. It manages user account, registration process, 
user info db schema and everything else as a whole that we can't easily 
customize and control.  The whole flow is consumer oriented. while our 
product is enterprise oriented. lots of customization is needed, many 
features needs to be added. We just need an authentication feature, but 
not other whole big chucks it provides.

2) when I run dex on my dev box, I blocked with a few weird errors, like 
"error getting signer: private key manager uninitialized". But can't 
figure out the root cause or simply resolve it even by reading code. 
It's too black box and will be a nightmare if we run into any problem in 
production.

Any other suggestion? Thanks!


Thanks
Gordon

**Comment by ericchiang** [comment]
If you have problems with dex please open an issue. It helps us make it better :)

As for other suggestions I don't have many more past my last comment.

**Comment by ericchiang** [comment]
Note  that I've added a OpenID Connect implementation to the osin framework which might work[0].

We don't have plans to add specific server support to this package, but may revisit it at a later time.

[0] https://github.com/RangelReale/osin/blob/master/example/openidconnect/openidconnect.go

**Comment by Grillz** [comment]
Figured I would leave https://github.com/ory/hydra here for the next guy. Its a very nice OIDC implementation, although its not compatible with this library at the moment, still digging into the cause there
