### ISSUE TITLE
jose: add JSON Web Signature utilities

### ISSUE THREAD

**Issue by ericchiang** [coreos/go-oidc#77]
Currently the only way to create a signed JWT is to use the `jose.Claims` object. However for https://github.com/coreos/dex/issues/418 we want to explicitly avoid this and operate on raw payloads (byte slices).

Add the ability to construct a signed JWT from a raw payload.

**Comment by bobbyrullo** [comment]
Is this still needed given the changes in #79?

**Comment by ericchiang** [comment]
Not for JWTs. I guess a better title would be "support creating JWSs"

**Comment by bobbyrullo** [comment]
I think that's a good idea. If that was done, it would probably make sense for the JWT creating code to use the JWS creating code.

Like 

``` 
// (pseudo Go)
NewSignedJWT(signer, obj){
  bytes = serializeToJson(obj)
  jws = NewSignerJWS(signer, bytes)
  return JWT(jws)
}
```

**Comment by ericchiang** [comment]
The new client no longer implements components the JOSE protocol. We recommend using https://github.com/square/go-jose instead.
