### ISSUE TITLE
jose: Supporting base64 encoded modulus

### ISSUE THREAD

**Issue by whitlockjc** [coreos/go-oidc#91]
I am trying to get [Cloudfoundry UAA](https://github.com/cloudfoundry/uaa) to work as an OIDC provider for Kubernetes.  Unfortunately, for UAA it appears the JWT Key modulus isn't base64url encoded and is only base64 encoded.  While I have created an [issue for this](https://github.com/cloudfoundry/uaa/issues/424) in the UAA repository, I was wondering if it would hurt anything to attempt to base64 decode the modulus whenever base64url decoding failed.  Thoughts?

**Comment by ericchiang** [comment]
We have an ongoing goal of switching to square's JOSE package when we get the chance (see #50). Ultimately we'd like to get away from maintaining JOSE and OAuth2 packages in this repo by swapping them out for better maintained Go implementations of these standards.

Supporting options that are off spec would mean breaking the ability to do this, so I'm very hesitant to entertain different decodings.

**Comment by whitlockjc** [comment]
I understand, it was just a quick fix for UAA support.  I don't see the harm since it would only be used when base64url encoding failed but I trust your judgement.  I have a workaround, serving a different `/token_keys` document that has the modulus base64url encoded.  Feel free to close this if you don't want to do this.  I'm not planning to argue.  ;)

**Comment by ericchiang** [comment]
> I understand, it was just a quick fix for UAA support. I don't see the harm since it would only be used when base64url encoding failed but I trust your judgement.

Just to reiterate the goal is for this logic to actually live in https://github.com/square/go-jose not this package. Allowing this then switching to that would be a pretty big breaking change.

Appreciate you opening this issue and sorry that it UAA is so... unique.

Yep, closing this one.

**Comment by whitlockjc** [comment]
No sweat.  I will get it working at some point.
